/*
 * wdt_regs_access.h
 *
 *  Created on: Apr 2, 2018
 *      Author: v.strukov
 */

#ifndef WDT_REGS_ACCESS_H_
#define WDT_REGS_ACCESS_H_

#include <platform/oi10/platform/reg_access/macros.h>

REG_READ(wd,WDOGLOAD,32)
REG_WRITE(wd,WDOGLOAD,32)

REG_READ(wd,WDOGVALUE,32)

REG_READ(wd,WDOGCONTROL,32)
REG_WRITE(wd,WDOGCONTROL,32)

REG_WRITE(wd,WDOGINTCLR,32)

REG_READ(wd,WDOGRIS,32)

REG_READ(wd,WDOGMIS,32)

REG_READ(wd,WDOGLOCK,32)
REG_WRITE(wd,WDOGLOCK,32)

REG_READ(wd,WDOGITCR,32)
REG_WRITE(wd,WDOGITCR,32)

REG_WRITE(wd,WDOGITOP,32)

REG_READ(wd,WDOGPERIPHID0,32)
REG_READ(wd,WDOGPERIPHID1,32)
REG_READ(wd,WDOGPERIPHID2,32)
REG_READ(wd,WDOGPERIPHID3,32)

REG_READ(wd,WDOGPCELLID0,32)
REG_READ(wd,WDOGPCELLID1,32)
REG_READ(wd,WDOGPCELLID2,32)
REG_READ(wd,WDOGPCELLID3,32)



#endif /* WDT_REGS_ACCESS_H_ */
