/*
 * regs_cldcr.h
 *
 *  Created on: May 14, 2018
 *      Author: d.arsentiev
 */

#ifndef REGS_CLDCR_H_
#define REGS_CLDCR_H_


BEGIN_ENUM( CLDCR_TCRREV_FIELD )
/* Version number */
DECLARE_ENUM_VAL( CLDCR_TCRREV_VNUMB_e,     23 )
DECLARE_ENUM_VAL( CLDCR_TCRREV_VNUMB_i,     IBM_BIT_INDEX( 32, CLDCR_TCRREV_VNUMB_e ) )
DECLARE_ENUM_VAL( CLDCR_TCRREV_VNUMB_n,     12 )
/* Revision number */
DECLARE_ENUM_VAL( CLDCR_TCRREV_RVNUMB_e,    32 )
DECLARE_ENUM_VAL( CLDCR_TCRREV_RVNUMB_i,    IBM_BIT_INDEX( 32, CLDCR_TCRREV_RVNUMB_e ) )
DECLARE_ENUM_VAL( CLDCR_TCRREV_RVNUMB_n,    8 )
END_ENUM( CLDCR_TCRREV_FIELD )


BEGIN_ENUM( CLDCR_ITRCTRL_FIELD )
/* CPU ITrace Enable */
DECLARE_ENUM_VAL( CLDCR_ITRCTRL_CPU_ITEN_e,         25 )
DECLARE_ENUM_VAL( CLDCR_ITRCTRL_CPU_ITEN_i,         IBM_BIT_INDEX( 32, CLDCR_ITRCTRL_CPU_ITEN_e ) )
DECLARE_ENUM_VAL( CLDCR_ITRCTRL_CPU_ITEN_n,         2 )
/* CPU0 ITrace Halt Enable (ITrace -> DBG_C470SDEBUGHALT) */
DECLARE_ENUM_VAL( CLDCR_ITRCTRL_CPU0_ITHTEN_e,      28 )
DECLARE_ENUM_VAL( CLDCR_ITRCTRL_CPU0_ITHTEN_i,      IBM_BIT_INDEX( 32, CLDCR_ITRCTRL_CPU0_ITHTEN_e ) )
DECLARE_ENUM_VAL( CLDCR_ITRCTRL_CPU0_ITHTEN_n,      1 )
/* CPU1 ITrace Halt Enable (ITrace -> DBG_C470SDEBUGHALT) */
DECLARE_ENUM_VAL( CLDCR_ITRCTRL_CPU1_ITHTEN_e,      29 )
DECLARE_ENUM_VAL( CLDCR_ITRCTRL_CPU1_ITHTEN_i,      IBM_BIT_INDEX( 32, CLDCR_ITRCTRL_CPU1_ITHTEN_e ) )
DECLARE_ENUM_VAL( CLDCR_ITRCTRL_CPU1_ITHTEN_n,      1 )
END_ENUM( CLDCR_ITRCTRL_FIELD )

BEGIN_ENUM( CLDCR_ITRCTRL_CPU_ITEN )
DECLARE_ENUM_VAL( CLDCR_ITRCTRL_CPU_ITEN_PPC0,  0b01 )
DECLARE_ENUM_VAL( CLDCR_ITRCTRL_CPU_ITEN_PPC1,  0b10 )
END_ENUM( CLDCR_ITRCTRL_CPU_ITEN )


BEGIN_ENUM( CLDCR_LTRCTRL_FIELD )
/* CPU0 LTrace Halt Enable (|LTRACE_COMPLETE[0:1] (LTrace0, LTrace1) -> DBG_C470SDEBUGHALT) */
DECLARE_ENUM_VAL( CLDCR_LTRCTRL_CPU0_LTEN_e,        28 )
DECLARE_ENUM_VAL( CLDCR_LTRCTRL_CPU0_LTEN_i,        IBM_BIT_INDEX( 32, CLDCR_LTRCTRL_CPU0_LTEN_e ) )
DECLARE_ENUM_VAL( CLDCR_LTRCTRL_CPU0_LTEN_n,        1 )
/* CPU1 LTrace Halt Enable (|LTRACE_COMPLETE[0:1] (LTrace0, LTrace1) -> DBG_C470SDEBUGHALT) */
DECLARE_ENUM_VAL( CLDCR_LTRCTRL_CPU1_LTEN_e,        29 )
DECLARE_ENUM_VAL( CLDCR_LTRCTRL_CPU1_LTEN_i,        IBM_BIT_INDEX( 32, CLDCR_LTRCTRL_CPU1_LTEN_e ) )
DECLARE_ENUM_VAL( CLDCR_LTRCTRL_CPU1_LTEN_n,        1 )
END_ENUM( CLDCR_LTRCTRL_FIELD )

BEGIN_ENUM( CLDCR_REG )
DECLARE_ENUM_VAL( CLDCR_TCRREV,     0x0 )   /* Revision number */
DECLARE_ENUM_VAL( CLDCR_ITRCTRL,    0x1 )   /* ITrace control  */
DECLARE_ENUM_VAL( CLDCR_LTRCTRL,    0x2 )   /* LTrace control  */
END_ENUM( CLDCR_REG )

BEGIN_ENUM( CLDCR_REG_DFLT )
DECLARE_ENUM_VAL( CLDCR_TCRREV_DFLT,    0x00000101 )
DECLARE_ENUM_VAL( CLDCR_ITRCTRL_DFLT,   0x00000000 )
DECLARE_ENUM_VAL( CLDCR_LTRCTRL_DFLT,   0x00000000 )
END_ENUM( CLDCR_REG_DFLT )


#endif /* REGS_CLDCR_H_ */

