/*
 * regs_plb4arb8m.h
 *
 *  Created on: May 4, 2018
 *      Author: d.arsentiev
 */

#ifndef REGS_PLB4ARB8M_H_
#define REGS_PLB4ARB8M_H_

#define PREV				0x2
#define PACR				0x3
#define PESR_RC				0x4
#define PESR_W				0x5
#define PEARL				0x6
#define PEARH				0x7

#define PLB4ARB8M_0_PREV	(DCR_PLB4ARB8M_0_BASE + PREV)
#define PLB4ARB8M_0_PACR	(DCR_PLB4ARB8M_0_BASE + PACR)
#define PLB4ARB8M_0_PESR_RC	(DCR_PLB4ARB8M_0_BASE + PESR_RC)
#define PLB4ARB8M_0_PESR_W	(DCR_PLB4ARB8M_0_BASE + PESR_W)
#define PLB4ARB8M_0_PEARL	(DCR_PLB4ARB8M_0_BASE + PEARL)
#define PLB4ARB8M_0_PEARH	(DCR_PLB4ARB8M_0_BASE + PEARH)

#define PLB4ARB8M_1_PREV	(DCR_PLB4ARB8M_1_BASE + PREV)
#define PLB4ARB8M_1_PACR	(DCR_PLB4ARB8M_1_BASE + PACR)
#define PLB4ARB8M_1_PESR_RC	(DCR_PLB4ARB8M_1_BASE + PESR_RC)
#define PLB4ARB8M_1_PESR_W	(DCR_PLB4ARB8M_1_BASE + PESR_W)
#define PLB4ARB8M_1_PEARL	(DCR_PLB4ARB8M_1_BASE + PEARL)
#define PLB4ARB8M_1_PEARH	(DCR_PLB4ARB8M_1_BASE + PEARH)

#define PLB4ARB8M_2_PREV	(DCR_PLB4ARB8M_2_BASE + PREV)
#define PLB4ARB8M_2_PACR	(DCR_PLB4ARB8M_2_BASE + PACR)
#define PLB4ARB8M_2_PESR_RC	(DCR_PLB4ARB8M_2_BASE + PESR_RC)
#define PLB4ARB8M_2_PESR_W	(DCR_PLB4ARB8M_2_BASE + PESR_W)
#define PLB4ARB8M_2_PEARL	(DCR_PLB4ARB8M_2_BASE + PEARL)
#define PLB4ARB8M_2_PEARH	(DCR_PLB4ARB8M_2_BASE + PEARH)

#endif /* REGS_PLB4ARB8M_H_ */
