#ifndef PLATFORM_INTERRUPTS_H
#define PLATFORM_INTERRUPTS_H

#define RUMBOOT_PLATFORM_NUM_IRQS 64
#define IRQ_ITIMER0  0
#define IRQ_ITIMER1  1
#define PPC_HIGH_LEVEL_INT (12)

#define CP0_RCV_INT  16
#define CP0_TRM_INT  17
#define CP1_RCV_INT  18
#define CP1_TRM_INT  19

#define PPC_LOW_LEVEL_INT (49)

#endif