/**
 * ppc_476fp_timer_fields.h
 */

#ifndef PPC_476FP_TIMER_FIELDS_H
#define PPC_476FP_TIMER_FIELDS_H


#include <common_macros/common_macros.h>
#include <arch/ppc/ibm_bit_ordering_macros.h>


BEGIN_ENUM( TIMER_TBL_FIELD )
DECLARE_ENUM_VAL( TIMER_TBL_e,  63 )
DECLARE_ENUM_VAL( TIMER_TBL_n,  32 )
DECLARE_ENUM_VAL( TIMER_TBL_i,  IBM_BIT_INDEX( 64, TIMER_TBL_e ) )
END_ENUM( TIMER_TBL_FIELD )


BEGIN_ENUM( TIMER_TBU_FIELD )
DECLARE_ENUM_VAL( TIMER_TBU_e,  63 )
DECLARE_ENUM_VAL( TIMER_TBU_n,  32 )
DECLARE_ENUM_VAL( TIMER_TBU_i,  IBM_BIT_INDEX( 64, TIMER_TBU_e ) )
END_ENUM( TIMER_TBU_FIELD )


BEGIN_ENUM( TIMER_DEC_FIELD )
DECLARE_ENUM_VAL( TIMER_DEC_e,  31 )
DECLARE_ENUM_VAL( TIMER_DEC_n,  32 )
DECLARE_ENUM_VAL( TIMER_DEC_i,  IBM_BIT_INDEX( 32, TIMER_DEC_e ) )
END_ENUM( TIMER_DEC_FIELD )


BEGIN_ENUM( TIMER_DECAR_FIELD )
DECLARE_ENUM_VAL( TIMER_DECAR_e,    31 )
DECLARE_ENUM_VAL( TIMER_DECAR_n,    32 )
DECLARE_ENUM_VAL( TIMER_DECAR_i,    IBM_BIT_INDEX( 32, TIMER_DECAR_e ) )
END_ENUM( TIMER_DECAR_FIELD )


BEGIN_ENUM( TIMER_TCR_FIELD )
DECLARE_ENUM_VAL( TIMER_TCR_WP_e,   33 )
DECLARE_ENUM_VAL( TIMER_TCR_WP_n,   2 )
DECLARE_ENUM_VAL( TIMER_TCR_WP_i,   IBM_BIT_INDEX( 64, TIMER_TCR_WP_e ) )

DECLARE_ENUM_VAL( TIMER_TCR_WRC_e,  35 )
DECLARE_ENUM_VAL( TIMER_TCR_WRC_n,  2 )
DECLARE_ENUM_VAL( TIMER_TCR_WRC_i,  IBM_BIT_INDEX( 64, TIMER_TCR_WRC_e ) )

DECLARE_ENUM_VAL( TIMER_TCR_WIE_e,  36 )
DECLARE_ENUM_VAL( TIMER_TCR_WIE_n,  1 )
DECLARE_ENUM_VAL( TIMER_TCR_WIE_i,  IBM_BIT_INDEX( 64, TIMER_TCR_WIE_e ) )

DECLARE_ENUM_VAL( TIMER_TCR_DIE_e,  37 )
DECLARE_ENUM_VAL( TIMER_TCR_DIE_n,  1 )
DECLARE_ENUM_VAL( TIMER_TCR_DIE_i,  IBM_BIT_INDEX( 64, TIMER_TCR_DIE_e ) )

DECLARE_ENUM_VAL( TIMER_TCR_FP_e,   39 )
DECLARE_ENUM_VAL( TIMER_TCR_FP_n,   2 )
DECLARE_ENUM_VAL( TIMER_TCR_FP_i,   IBM_BIT_INDEX( 64, TIMER_TCR_FP_e ) )

DECLARE_ENUM_VAL( TIMER_TCR_FIE_e,  40 )
DECLARE_ENUM_VAL( TIMER_TCR_FIE_n,  1 )
DECLARE_ENUM_VAL( TIMER_TCR_FIE_i,  IBM_BIT_INDEX( 64, TIMER_TCR_FIE_e ) )

DECLARE_ENUM_VAL( TIMER_TCR_ARE_e,  41 )
DECLARE_ENUM_VAL( TIMER_TCR_ARE_n,  1 )
DECLARE_ENUM_VAL( TIMER_TCR_ARE_i,  IBM_BIT_INDEX( 64, TIMER_TCR_ARE_e ) )
END_ENUM( TIMER_TCR_FIELD )

BEGIN_ENUM( TIMER_TCR_WP )
DECLARE_ENUM_VAL( TIMER_TCR_WP_2pow20_clocks,   0b00 )
DECLARE_ENUM_VAL( TIMER_TCR_WP_2pow24_clocks,   0b01 )
DECLARE_ENUM_VAL( TIMER_TCR_WP_2pow28_clocks,   0b10 )
DECLARE_ENUM_VAL( TIMER_TCR_WP_2pow32_clocks,   0b11 )
END_ENUM( TIMER_TCR_WP )

BEGIN_ENUM( TIMER_TCR_WRC )
DECLARE_ENUM_VAL( TIMER_TCR_WRC_No_WD_reset,    0b00 )
DECLARE_ENUM_VAL( TIMER_TCR_WRC_Core_reset,     0b01 )
DECLARE_ENUM_VAL( TIMER_TCR_WRC_Chip_reset,     0b10 )
DECLARE_ENUM_VAL( TIMER_TCR_WRC_System_reset,   0b11 )
END_ENUM( TIMER_TCR_WRC )

BEGIN_ENUM( TIMER_TCR_FP )
DECLARE_ENUM_VAL( TIMER_TCR_FP_2pow12_clocks,   0b00 )
DECLARE_ENUM_VAL( TIMER_TCR_FP_2pow16_clocks,   0b01 )
DECLARE_ENUM_VAL( TIMER_TCR_FP_2pow20_clocks,   0b10 )
DECLARE_ENUM_VAL( TIMER_TCR_FP_2pow24_clocks,   0b11 )
END_ENUM( TIMER_TCR_FP )


BEGIN_ENUM( TIMER_TSR_FIELD )
DECLARE_ENUM_VAL( TIMER_TSR_EVW_e,  32 )
DECLARE_ENUM_VAL( TIMER_TSR_EVW_n,  1 )
DECLARE_ENUM_VAL( TIMER_TSR_EVW_i,  IBM_BIT_INDEX( 64, TIMER_TSR_EVW_e ) )

DECLARE_ENUM_VAL( TIMER_TSR_WIS_e,  33 )
DECLARE_ENUM_VAL( TIMER_TSR_WIS_n,  1 )
DECLARE_ENUM_VAL( TIMER_TSR_WIS_i,  IBM_BIT_INDEX( 64, TIMER_TSR_WIS_e ) )

DECLARE_ENUM_VAL( TIMER_TSR_WRS_e,  35 )
DECLARE_ENUM_VAL( TIMER_TSR_WRS_n,  2 )
DECLARE_ENUM_VAL( TIMER_TSR_WRS_i,  IBM_BIT_INDEX( 64, TIMER_TSR_WRS_e ) )

DECLARE_ENUM_VAL( TIMER_TSR_DIS_e,  36 )
DECLARE_ENUM_VAL( TIMER_TSR_DIS_n,  1 )
DECLARE_ENUM_VAL( TIMER_TSR_DIS_i,  IBM_BIT_INDEX( 64, TIMER_TSR_DIS_e ) )

DECLARE_ENUM_VAL( TIMER_TSR_FIS_e,  37 )
DECLARE_ENUM_VAL( TIMER_TSR_FIS_n,  1 )
DECLARE_ENUM_VAL( TIMER_TSR_FIS_i,  IBM_BIT_INDEX( 64, TIMER_TSR_FIS_e ) )
END_ENUM( TIMER_TSR_FIELD )

BEGIN_ENUM( TIMER_TSR_WIS )
DECLARE_ENUM_VAL( TIMER_TSR_WIS_WD_exception_not_occurred,  0b0 )
DECLARE_ENUM_VAL( TIMER_TSR_WIS_WD_exception_occurred,      0b1 )
END_ENUM( TIMER_TSR_WIS )

BEGIN_ENUM( TIMER_TSR_WRS )
DECLARE_ENUM_VAL( TIMER_TCR_WRS_No_WD_reset,    0b00 )
DECLARE_ENUM_VAL( TIMER_TCR_WRS_Core_reset,     0b01 )
DECLARE_ENUM_VAL( TIMER_TCR_WRS_Chip_reset,     0b10 )
DECLARE_ENUM_VAL( TIMER_TCR_WRS_System_reset,   0b11 )
END_ENUM( TIMER_TSR_WRS )

BEGIN_ENUM( TIMER_TSR_DIS )
DECLARE_ENUM_VAL( TIMER_TSR_DIS_DEC_exception_not_occurred, 0b0 )
DECLARE_ENUM_VAL( TIMER_TSR_DIS_DEC_exception_occurred,     0b1 )
END_ENUM( TIMER_TSR_DIS )

BEGIN_ENUM( TIMER_TSR_FIS )
DECLARE_ENUM_VAL( TIMER_TSR_FIS_FIT_exception_not_occurred, 0b0 )
DECLARE_ENUM_VAL( TIMER_TSR_FIS_FIT_exception_occurred,     0b1 )
END_ENUM( TIMER_TSR_FIS )


#endif // PPC_476FP_TIMER_FIELDS_H
