#ifndef __SCTL_REG_ACCESS_H__
#define __SCTL_REG_ACCESS_H__

#include <platform/oi10/platform/mivem_macro.h>
#include <platform/oi10/platform/mivem_regs_access.h>
#include <platform/oi10/platform/sctl/sctl_regs.h>
#include <platform/oi10/platform/boost/preprocessor/cat.hpp>
#include <platform/oi10/platform/boost/preprocessor/iteration/local.hpp>


#define SCTLx_IFSYS_IO_CONF(INDEX) \
    BOOST_PP_CAT(SCTLx_IFSYS_IO_CONF, INDEX)

#define SCTL_REG_WRITE(REG_NAME, VALUE) \
    BOOST_PP_CAT(SCTL_write_, REG_NAME)(SCTL_BASE, VALUE)

#define SCTLx_MLT_IO_CONF(INDEX) \
    BOOST_PP_CAT(SCTLx_MLT_IO_CONF, INDEX)

REG_READ(SCTL, SCTLx_BOOT_CFG, 32)

REG_READ(SCTL, SCTLx_PLL_STATE, 32)

REG_READ(SCTL, SCTLx_SYS_CONF0, 32)
REG_WRITE(SCTL, SCTLx_SYS_CONF0, 32)

REG_READ(SCTL, SCTLx_RST_MON, 32)

REG_READ(SCTL, SCTLx_RST_CTRL, 32)
REG_WRITE(SCTL, SCTLx_RST_CTRL, 32)

REG_READ(SCTL, SCTLx_PPC_SLP_CTRL, 32)
REG_WRITE(SCTL, SCTLx_PPC_SLP_CTRL, 32)

REG_READ(SCTL, SCTLx_SRAM_NOR_CTRL, 32)
REG_WRITE(SCTL, SCTLx_SRAM_NOR_CTRL, 32)

REG_READ(SCTL, SCTLx_BISR_IM0, 32)
REG_WRITE(SCTL, SCTLx_BISR_IM0, 32)

REG_READ(SCTL, SCTLx_BISR_L2C_0, 32)
REG_WRITE(SCTL, SCTLx_BISR_L2C_0, 32)

REG_READ(SCTL, SCTLx_BISR_L2C_1, 32)
REG_WRITE(SCTL, SCTLx_BISR_L2C_1, 32)

REG_READ(SCTL, SCTLx_BISR_DSP0_IM1_0, 32)
REG_WRITE(SCTL, SCTLx_BISR_DSP0_IM1_0, 32)

REG_READ(SCTL, SCTLx_BISR_DSP0_IM1_1, 32)
REG_WRITE(SCTL, SCTLx_BISR_DSP0_IM1_1, 32)

REG_READ(SCTL, SCTLx_BISR_DSP0_L2C, 32)
REG_WRITE(SCTL, SCTLx_BISR_DSP0_L2C, 32)

REG_READ(SCTL, SCTLx_BISR_DSP1_IM1_0, 32)
REG_WRITE(SCTL, SCTLx_BISR_DSP1_IM1_0, 32)

REG_READ(SCTL, SCTLx_BISR_DSP1_IM1_1, 32)
REG_WRITE(SCTL, SCTLx_BISR_DSP1_IM1_1, 32)

REG_READ(SCTL, SCTLx_BISR_DSP1_L2C, 32)
REG_WRITE(SCTL, SCTLx_BISR_DSP1_L2C, 32)

#define SCTLx_IFSYS_IO_CONFi_READ(i, z) \
REG_READ_ADDR_NAME(SCTL, SCTLx_IFSYS_IO_CONFx(i), SCTLx_IFSYS_IO_CONF##i, 32)
#define SCTLx_IFSYS_IO_CONFi_WRITE(i, z) \
REG_WRITE_ADDR_NAME(SCTL, SCTLx_IFSYS_IO_CONFx(i), SCTLx_IFSYS_IO_CONF##i, 32)

REPEAT( SCTLx_IFSYS_IO_CONF_REGS_COUNT, SCTLx_IFSYS_IO_CONFi_READ, z )
REPEAT( SCTLx_IFSYS_IO_CONF_REGS_COUNT, SCTLx_IFSYS_IO_CONFi_WRITE, z )

#define SCTLx_MLT_IO_CONFi_READ(i, z) \
REG_READ_ADDR_NAME(SCTL, SCTLx_MLT_IO_CONFx(i), SCTLx_MLT_IO_CONF##i, 32)
#define SCTLx_MLT_IO_CONFi_WRITE(i, z) \
REG_WRITE_ADDR_NAME(SCTL, SCTLx_MLT_IO_CONFx(i), SCTLx_MLT_IO_CONF##i, 32)

REPEAT( SCTLx_MLT_IO_CONF_REGS_COUNT, SCTLx_MLT_IO_CONFi_READ, z )
REPEAT( SCTLx_MLT_IO_CONF_REGS_COUNT, SCTLx_MLT_IO_CONFi_WRITE, z )

REG_READ(SCTL, SCTLx_INTSTA_DSP2CPU, 32)

REG_READ(SCTL, SCTLx_INTCLR_DSP2CPU, 32)
REG_WRITE(SCTL, SCTLx_INTCLR_DSP2CPU, 32)

REG_READ(SCTL, SCTLx_INTREQ_CPU2DSP, 32)
REG_WRITE(SCTL, SCTLx_INTREQ_CPU2DSP, 32)

//
//REG_READ(SCTL, SCTLx_DSP0_NMC0_NMI, 32)
//REG_WRITE(SCTL, SCTLx_DSP0_NMC0_NMI, 32)
//
//REG_READ(SCTL, SCTLx_DSP0_NMC1_NMI, 32)
//REG_WRITE(SCTL, SCTLx_DSP0_NMC1_NMI, 32)
//
//REG_READ(SCTL, SCTLx_DSP0_NMC0_INTL, 32)
//REG_WRITE(SCTL, SCTLx_DSP0_NMC0_INTL, 32)
//
//REG_READ(SCTL, SCTLx_DSP0_NMC1_INTL, 32)
//REG_WRITE(SCTL, SCTLx_DSP0_NMC1_INTL, 32)
//
//REG_READ(SCTL, SCTLx_DSP0_NMC0_INTH, 32)
//REG_WRITE(SCTL, SCTLx_DSP0_NMC0_INTH, 32)
//
//REG_READ(SCTL, SCTLx_DSP0_NMC1_INTH, 32)
//REG_WRITE(SCTL, SCTLx_DSP0_NMC1_INTH, 32)
//
//REG_READ(SCTL, SCTLx_DSP0_NMC0_INTLCLR, 32)
//REG_WRITE(SCTL, SCTLx_DSP0_NMC0_INTLCLR, 32)
//
//REG_READ(SCTL, SCTLx_DSP0_NMC1_INTLCLR, 32)
//REG_WRITE(SCTL, SCTLx_DSP0_NMC1_INTLCLR, 32)
//
//REG_READ(SCTL, SCTLx_DSP0_NMC0_INTHCLR, 32)
//REG_WRITE(SCTL, SCTLx_DSP0_NMC0_INTHCLR, 32)
//
//REG_READ(SCTL, SCTLx_DSP0_NMC1_INTHCLR, 32)
//REG_WRITE(SCTL, SCTLx_DSP0_NMC1_INTHCLR, 32)
//
//REG_READ(SCTL, SCTLx_DSP0_NMC0_RST, 32)
//REG_WRITE(SCTL, SCTLx_DSP0_NMC0_RST, 32)
//
//REG_READ(SCTL, SCTLx_DSP0_TD, 32)
//
//REG_READ(SCTL, SCTLx_DSP0_ADR, 32)
//REG_WRITE(SCTL, SCTLx_DSP0_ADR, 32)
//
//REG_READ(SCTL, SCTLx_DSP1_NMC0_NMI, 32)
//REG_WRITE(SCTL, SCTLx_DSP1_NMC0_NMI, 32)
//
//REG_READ(SCTL, SCTLx_DSP1_NMC1_NMI, 32)
//REG_WRITE(SCTL, SCTLx_DSP1_NMC1_NMI, 32)
//
//REG_READ(SCTL, SCTLx_DSP1_NMC0_INTL, 32)
//REG_WRITE(SCTL, SCTLx_DSP1_NMC0_INTL, 32)
//
//REG_READ(SCTL, SCTLx_DSP1_NMC1_INTL, 32)
//REG_WRITE(SCTL, SCTLx_DSP1_NMC1_INTL, 32)
//
//REG_READ(SCTL, SCTLx_DSP1_NMC0_INTH, 32)
//REG_WRITE(SCTL, SCTLx_DSP1_NMC0_INTH, 32)
//
//REG_READ(SCTL, SCTLx_DSP1_NMC1_INTH, 32)
//REG_WRITE(SCTL, SCTLx_DSP1_NMC1_INTH, 32)
//
//REG_READ(SCTL, SCTLx_DSP1_NMC0_INTLCLR, 32)
//REG_WRITE(SCTL, SCTLx_DSP1_NMC0_INTLCLR, 32)
//
//REG_READ(SCTL, SCTLx_DSP1_NMC1_INTLCLR, 32)
//REG_WRITE(SCTL, SCTLx_DSP1_NMC1_INTLCLR, 32)
//
//REG_READ(SCTL, SCTLx_DSP1_NMC0_INTHCLR, 32)
//REG_WRITE(SCTL, SCTLx_DSP1_NMC0_INTHCLR, 32)
//
//REG_READ(SCTL, SCTLx_DSP1_NMC1_INTHCLR, 32)
//REG_WRITE(SCTL, SCTLx_DSP1_NMC1_INTHCLR, 32)
//
//REG_READ(SCTL, SCTLx_DSP1_NMC0_RST, 32)
//REG_WRITE(SCTL, SCTLx_DSP1_NMC0_RST, 32)
//
//REG_READ(SCTL, SCTLx_DSP1_TD, 32)
//
//REG_READ(SCTL, SCTLx_DSP1_ADR, 32)
//REG_WRITE(SCTL, SCTLx_DSP1_ADR, 32)

REG_READ(SCTL, SCTLx_USB_BIST_CNTRL, 32)
REG_WRITE(SCTL, SCTLx_USB_BIST_CNTRL, 32)

REG_READ(SCTL, SCTLx_EM0_BIST_CNTRL, 32)
REG_WRITE(SCTL, SCTLx_EM0_BIST_CNTRL, 32)

REG_READ(SCTL, SCTLx_EM1_BIST_CNTRL, 32)
REG_WRITE(SCTL, SCTLx_EM1_BIST_CNTRL, 32)

REG_READ(SCTL, SCTLx_MISC_IO_CONF0, 32)
REG_WRITE(SCTL, SCTLx_MISC_IO_CONF0, 32)

REG_READ(SCTL, SCTLx_MLT_ADR_MSB0, 32)
REG_WRITE(SCTL, SCTLx_MLT_ADR_MSB0, 32)

REG_READ(SCTL, SCTLx_MLT_ADR_MSB1, 32)
REG_WRITE(SCTL, SCTLx_MLT_ADR_MSB1, 32)







#endif // __SCTL_REGS_ACCESS_H__
