/**
 * ppc_476fp_itrpt_fields.h
 */

#ifndef PPC_476FP_ITRPT_FIELDS_H
#define PPC_476FP_ITRPT_FIELDS_H


#include <platform/common_macros/common_macros.h>
#include <platform/arch/ppc/ibm_bit_ordering_macros.h>


BEGIN_ENUM( ITRPT_XSR_FIELD )
DECLARE_ENUM_VAL( ITRPT_XSR_WE_e,   45 )
DECLARE_ENUM_VAL( ITRPT_XSR_WE_n,   1 )
DECLARE_ENUM_VAL( ITRPT_XSR_WE_i,   IBM_BIT_INDEX( 64, ITRPT_XSR_WE_e ) )

DECLARE_ENUM_VAL( ITRPT_XSR_CE_e,   46 )
DECLARE_ENUM_VAL( ITRPT_XSR_CE_n,   1 )
DECLARE_ENUM_VAL( ITRPT_XSR_CE_i,   IBM_BIT_INDEX( 64, ITRPT_XSR_CE_e ) )

DECLARE_ENUM_VAL( ITRPT_XSR_EE_e,   48 )
DECLARE_ENUM_VAL( ITRPT_XSR_EE_n,   1 )
DECLARE_ENUM_VAL( ITRPT_XSR_EE_i,   IBM_BIT_INDEX( 64, ITRPT_XSR_EE_e ) )

DECLARE_ENUM_VAL( ITRPT_XSR_PR_e,   49 )
DECLARE_ENUM_VAL( ITRPT_XSR_PR_n,   1 )
DECLARE_ENUM_VAL( ITRPT_XSR_PR_i,   IBM_BIT_INDEX( 64, ITRPT_XSR_PR_e ) )

DECLARE_ENUM_VAL( ITRPT_XSR_FP_e,   50 )
DECLARE_ENUM_VAL( ITRPT_XSR_FP_n,   1 )
DECLARE_ENUM_VAL( ITRPT_XSR_FP_i,   IBM_BIT_INDEX( 64, ITRPT_XSR_FP_e ) )

DECLARE_ENUM_VAL( ITRPT_XSR_ME_e,   51 )
DECLARE_ENUM_VAL( ITRPT_XSR_ME_n,   1 )
DECLARE_ENUM_VAL( ITRPT_XSR_ME_i,   IBM_BIT_INDEX( 64, ITRPT_XSR_ME_e ) )

DECLARE_ENUM_VAL( ITRPT_XSR_FE0_e,  52 )
DECLARE_ENUM_VAL( ITRPT_XSR_FE0_n,  1 )
DECLARE_ENUM_VAL( ITRPT_XSR_FE0_i,  IBM_BIT_INDEX( 64, ITRPT_XSR_FE0_e ) )

DECLARE_ENUM_VAL( ITRPT_XSR_DWE_e,  53 )
DECLARE_ENUM_VAL( ITRPT_XSR_DWE_n,  1 )
DECLARE_ENUM_VAL( ITRPT_XSR_DWE_i,  IBM_BIT_INDEX( 64, ITRPT_XSR_DWE_e ) )

DECLARE_ENUM_VAL( ITRPT_XSR_DE_e,   54 )
DECLARE_ENUM_VAL( ITRPT_XSR_DE_n,   1 )
DECLARE_ENUM_VAL( ITRPT_XSR_DE_i,   IBM_BIT_INDEX( 64, ITRPT_XSR_DE_e ) )

DECLARE_ENUM_VAL( ITRPT_XSR_FE1_e,  55 )
DECLARE_ENUM_VAL( ITRPT_XSR_FE1_n,  1 )
DECLARE_ENUM_VAL( ITRPT_XSR_FE1_i,  IBM_BIT_INDEX( 64, ITRPT_XSR_FE1_e ) )

DECLARE_ENUM_VAL( ITRPT_XSR_IS_e,   58 )
DECLARE_ENUM_VAL( ITRPT_XSR_IS_n,   1 )
DECLARE_ENUM_VAL( ITRPT_XSR_IS_i,   IBM_BIT_INDEX( 64, ITRPT_XSR_IS_e ) )

DECLARE_ENUM_VAL( ITRPT_XSR_DS_e,   59 )
DECLARE_ENUM_VAL( ITRPT_XSR_DS_n,   1 )
DECLARE_ENUM_VAL( ITRPT_XSR_DS_i,   IBM_BIT_INDEX( 64, ITRPT_XSR_DS_e ) )

DECLARE_ENUM_VAL( ITRPT_XSR_PMM_e,  61 )
DECLARE_ENUM_VAL( ITRPT_XSR_PMM_n,  1 )
DECLARE_ENUM_VAL( ITRPT_XSR_PMM_i,  IBM_BIT_INDEX( 64, ITRPT_XSR_PMM_e ) )
END_ENUM( ITRPT_XSR_FIELD )


BEGIN_ENUM( ITRPT_XSRR0_FIELD )
DECLARE_ENUM_VAL( ITRPT_XSRR0_ADDR_e,   61 )
DECLARE_ENUM_VAL( ITRPT_XSRR0_ADDR_n,   30 )
DECLARE_ENUM_VAL( ITRPT_XSRR0_ADDR_i,   IBM_BIT_INDEX( 64, ITRPT_XSRR0_ADDR_e ) )
END_ENUM( ITRPT_XSRR0_FIELD )


BEGIN_ENUM( ITRPT_IVPR_FIELD )
DECLARE_ENUM_VAL( ITRPT_IVPR_ADDR_e,    47 )
DECLARE_ENUM_VAL( ITRPT_IVPR_ADDR_n,    16 )
DECLARE_ENUM_VAL( ITRPT_IVPR_ADDR_i,    IBM_BIT_INDEX( 64, ITRPT_IVPR_ADDR_e ) )
END_ENUM( ITRPT_IVPR_FIELD )


BEGIN_ENUM( ITRPT_IVORn_FIELD )
DECLARE_ENUM_VAL( ITRPT_IVORn_OFFSET_e, 59 )
DECLARE_ENUM_VAL( ITRPT_IVORn_OFFSET_n, 12 )
DECLARE_ENUM_VAL( ITRPT_IVORn_OFFSET_i, IBM_BIT_INDEX( 64, ITRPT_IVORn_OFFSET_e ) )
END_ENUM( ITRPT_IVORn_FIELD )


BEGIN_ENUM( ITRPT_ESR_FIELD )
DECLARE_ENUM_VAL( ITRPT_ESR_ISMC_e, 32 )
DECLARE_ENUM_VAL( ITRPT_ESR_ISMC_n, 1 )
DECLARE_ENUM_VAL( ITRPT_ESR_ISMC_i, IBM_BIT_INDEX( 64, ITRPT_ESR_ISMC_e ) )

DECLARE_ENUM_VAL( ITRPT_ESR_SS_e,   33 )
DECLARE_ENUM_VAL( ITRPT_ESR_SS_n,   1 )
DECLARE_ENUM_VAL( ITRPT_ESR_SS_i,   IBM_BIT_INDEX( 64, ITRPT_ESR_SS_e ) )

DECLARE_ENUM_VAL( ITRPT_ESR_POT1_e, 34 )
DECLARE_ENUM_VAL( ITRPT_ESR_POT1_n, 1 )
DECLARE_ENUM_VAL( ITRPT_ESR_POT1_i, IBM_BIT_INDEX( 64, ITRPT_ESR_POT1_e ) )

DECLARE_ENUM_VAL( ITRPT_ESR_POT2_e, 35 )
DECLARE_ENUM_VAL( ITRPT_ESR_POT2_n, 1 )
DECLARE_ENUM_VAL( ITRPT_ESR_POT2_i, IBM_BIT_INDEX( 64, ITRPT_ESR_POT2_e ) )

DECLARE_ENUM_VAL( ITRPT_ESR_PIL_e,  36 )
DECLARE_ENUM_VAL( ITRPT_ESR_PIL_n,  1 )
DECLARE_ENUM_VAL( ITRPT_ESR_PIL_i,  IBM_BIT_INDEX( 64, ITRPT_ESR_PIL_e ) )

DECLARE_ENUM_VAL( ITRPT_ESR_PPR_e,  37 )
DECLARE_ENUM_VAL( ITRPT_ESR_PPR_n,  1 )
DECLARE_ENUM_VAL( ITRPT_ESR_PPR_i,  IBM_BIT_INDEX( 64, ITRPT_ESR_PPR_e ) )

DECLARE_ENUM_VAL( ITRPT_ESR_PTR_e,  38 )
DECLARE_ENUM_VAL( ITRPT_ESR_PTR_n,  1 )
DECLARE_ENUM_VAL( ITRPT_ESR_PTR_i,  IBM_BIT_INDEX( 64, ITRPT_ESR_PTR_e ) )

DECLARE_ENUM_VAL( ITRPT_ESR_FP_e,   39 )
DECLARE_ENUM_VAL( ITRPT_ESR_FP_n,   1 )
DECLARE_ENUM_VAL( ITRPT_ESR_FP_i,   IBM_BIT_INDEX( 64, ITRPT_ESR_FP_e ) )

DECLARE_ENUM_VAL( ITRPT_ESR_ST_e,   40 )
DECLARE_ENUM_VAL( ITRPT_ESR_ST_n,   1 )
DECLARE_ENUM_VAL( ITRPT_ESR_ST_i,   IBM_BIT_INDEX( 64, ITRPT_ESR_ST_e ) )

DECLARE_ENUM_VAL( ITRPT_ESR_DLK_e,  43 )
DECLARE_ENUM_VAL( ITRPT_ESR_DLK_n,  2 )
DECLARE_ENUM_VAL( ITRPT_ESR_DLK_i,  IBM_BIT_INDEX( 64, ITRPT_ESR_DLK_e ) )

DECLARE_ENUM_VAL( ITRPT_ESR_AP_e,   44 )
DECLARE_ENUM_VAL( ITRPT_ESR_AP_n,   1 )
DECLARE_ENUM_VAL( ITRPT_ESR_AP_i,   IBM_BIT_INDEX( 64, ITRPT_ESR_AP_e ) )

DECLARE_ENUM_VAL( ITRPT_ESR_PUO_e,  45 )
DECLARE_ENUM_VAL( ITRPT_ESR_PUO_n,  1 )
DECLARE_ENUM_VAL( ITRPT_ESR_PUO_i,  IBM_BIT_INDEX( 64, ITRPT_ESR_PUO_e ) )

DECLARE_ENUM_VAL( ITRPT_ESR_BO_e,   46 )
DECLARE_ENUM_VAL( ITRPT_ESR_BO_n,   1 )
DECLARE_ENUM_VAL( ITRPT_ESR_BO_i,   IBM_BIT_INDEX( 64, ITRPT_ESR_BO_e ) )

DECLARE_ENUM_VAL( ITRPT_ESR_PIE_e,  47 )
DECLARE_ENUM_VAL( ITRPT_ESR_PIE_n,  1 )
DECLARE_ENUM_VAL( ITRPT_ESR_PIE_i,  IBM_BIT_INDEX( 64, ITRPT_ESR_PIE_e ) )

DECLARE_ENUM_VAL( ITRPT_ESR_PCRE_e, 59 )
DECLARE_ENUM_VAL( ITRPT_ESR_PCRE_n, 1 )
DECLARE_ENUM_VAL( ITRPT_ESR_PCRE_i, IBM_BIT_INDEX( 64, ITRPT_ESR_PCRE_e ) )

DECLARE_ENUM_VAL( ITRPT_ESR_PCMP_e, 60 )
DECLARE_ENUM_VAL( ITRPT_ESR_PCMP_n, 1 )
DECLARE_ENUM_VAL( ITRPT_ESR_PCMP_i, IBM_BIT_INDEX( 64, ITRPT_ESR_PCMP_e ) )

DECLARE_ENUM_VAL( ITRPT_ESR_PCRF_e, 63 )
DECLARE_ENUM_VAL( ITRPT_ESR_PCRF_n, 1 )
DECLARE_ENUM_VAL( ITRPT_ESR_PCRF_i, IBM_BIT_INDEX( 64, ITRPT_ESR_PCRF_e ) )
END_ENUM( ITRPT_ESR_FIELD )

BEGIN_ENUM( ITRPT_ESR_DLK )
DECLARE_ENUM_VAL( ITRPT_ESR_DLK_not_occur,      0b00 )
DECLARE_ENUM_VAL( ITRPT_ESR_DLK_dcbf_issued,    0b01 )
DECLARE_ENUM_VAL( ITRPT_ESR_DLK_icbi_issued,    0b10 )
END_ENUM( ITRPT_ESR_DLK )


BEGIN_ENUM( ITRPT_MCSR_FIELD )
DECLARE_ENUM_VAL( ITRPT_MCSR_MCS_e, 32 )
DECLARE_ENUM_VAL( ITRPT_MCSR_MCS_n, 1 )
DECLARE_ENUM_VAL( ITRPT_MCSR_MCS_i, IBM_BIT_INDEX( 64, ITRPT_MCSR_MCS_e ) )

DECLARE_ENUM_VAL( ITRPT_MCSR_TLB_e, 36 )
DECLARE_ENUM_VAL( ITRPT_MCSR_TLB_n, 1 )
DECLARE_ENUM_VAL( ITRPT_MCSR_TLB_i, IBM_BIT_INDEX( 64, ITRPT_MCSR_TLB_e ) )

DECLARE_ENUM_VAL( ITRPT_MCSR_IC_e,  37 )
DECLARE_ENUM_VAL( ITRPT_MCSR_IC_n,  1 )
DECLARE_ENUM_VAL( ITRPT_MCSR_IC_i,  IBM_BIT_INDEX( 64, ITRPT_MCSR_IC_e ) )

DECLARE_ENUM_VAL( ITRPT_MCSR_DC_e,  38 )
DECLARE_ENUM_VAL( ITRPT_MCSR_DC_n,  1 )
DECLARE_ENUM_VAL( ITRPT_MCSR_DC_i,  IBM_BIT_INDEX( 64, ITRPT_MCSR_DC_e ) )

DECLARE_ENUM_VAL( ITRPT_MCSR_GPR_e, 39 )
DECLARE_ENUM_VAL( ITRPT_MCSR_GPR_n, 1 )
DECLARE_ENUM_VAL( ITRPT_MCSR_GPR_i, IBM_BIT_INDEX( 64, ITRPT_MCSR_GPR_e ) )

DECLARE_ENUM_VAL( ITRPT_MCSR_FPR_e, 40 )
DECLARE_ENUM_VAL( ITRPT_MCSR_FPR_n, 1 )
DECLARE_ENUM_VAL( ITRPT_MCSR_FPR_i, IBM_BIT_INDEX( 64, ITRPT_MCSR_FPR_e ) )

DECLARE_ENUM_VAL( ITRPT_MCSR_IMP_e, 41 )
DECLARE_ENUM_VAL( ITRPT_MCSR_IMP_n, 1 )
DECLARE_ENUM_VAL( ITRPT_MCSR_IMP_i, IBM_BIT_INDEX( 64, ITRPT_MCSR_IMP_e ) )

DECLARE_ENUM_VAL( ITRPT_MCSR_L2_e,  42 )
DECLARE_ENUM_VAL( ITRPT_MCSR_L2_n,  1 )
DECLARE_ENUM_VAL( ITRPT_MCSR_L2_i,  IBM_BIT_INDEX( 64, ITRPT_MCSR_L2_e ) )

DECLARE_ENUM_VAL( ITRPT_MCSR_DCR_e, 43 )
DECLARE_ENUM_VAL( ITRPT_MCSR_DCR_n, 1 )
DECLARE_ENUM_VAL( ITRPT_MCSR_DCR_i, IBM_BIT_INDEX( 64, ITRPT_MCSR_DCR_e ) )
END_ENUM( ITRPT_MCSR_FIELD )


#endif // PPC_476FP_ITRPT_FIELDS_H
