/*
 * ppc_476fp_fpu_fields.h
 *
 *  Created on: Jul 13, 2018
 *      Author: d.arsentiev
 */

#ifndef PPC_476FP_FPU_FIELDS_H_
#define PPC_476FP_FPU_FIELDS_H_

#include <platform/common_macros/common_macros.h>
#include <platform/arch/ppc/ibm_bit_ordering_macros.h>


/* FPSCR bits */
BEGIN_ENUM( FPU_FPSCR_FIELD )
    DECLARE_ENUM_VAL( FPU_FPSCR_FX_e,       32                                      )
    DECLARE_ENUM_VAL( FPU_FPSCR_FX_n,       1                                       )
    DECLARE_ENUM_VAL( FPU_FPSCR_FX_i,       IBM_BIT_INDEX( 64, FPU_FPSCR_FX_e     ) )
    DECLARE_ENUM_VAL( FPU_FPSCR_FEX_e,      33                                      )
    DECLARE_ENUM_VAL( FPU_FPSCR_FEX_n,      1                                       )
    DECLARE_ENUM_VAL( FPU_FPSCR_FEX_i,      IBM_BIT_INDEX( 64, FPU_FPSCR_FEX_e    ) )
    DECLARE_ENUM_VAL( FPU_FPSCR_VX_e,       34                                      )
    DECLARE_ENUM_VAL( FPU_FPSCR_VX_n,       1                                       )
    DECLARE_ENUM_VAL( FPU_FPSCR_VX_i,       IBM_BIT_INDEX( 64, FPU_FPSCR_VX_e     ) )
    DECLARE_ENUM_VAL( FPU_FPSCR_OX_e,       35                                      )
    DECLARE_ENUM_VAL( FPU_FPSCR_OX_n,       1                                       )
    DECLARE_ENUM_VAL( FPU_FPSCR_OX_i,       IBM_BIT_INDEX( 64, FPU_FPSCR_OX_e     ) )
    DECLARE_ENUM_VAL( FPU_FPSCR_UX_e,       36                                      )
    DECLARE_ENUM_VAL( FPU_FPSCR_UX_n,       1                                       )
    DECLARE_ENUM_VAL( FPU_FPSCR_UX_i,       IBM_BIT_INDEX( 64, FPU_FPSCR_UX_e     ) )
    DECLARE_ENUM_VAL( FPU_FPSCR_ZX_e,       37                                      )
    DECLARE_ENUM_VAL( FPU_FPSCR_ZX_n,       1                                       )
    DECLARE_ENUM_VAL( FPU_FPSCR_ZX_i,       IBM_BIT_INDEX( 64, FPU_FPSCR_ZX_e     ) )
    DECLARE_ENUM_VAL( FPU_FPSCR_XX_e,       38                                      )
    DECLARE_ENUM_VAL( FPU_FPSCR_XX_n,       1                                       )
    DECLARE_ENUM_VAL( FPU_FPSCR_XX_i,       IBM_BIT_INDEX( 64, FPU_FPSCR_XX_e     ) )
    DECLARE_ENUM_VAL( FPU_FPSCR_VXSNAN_e,   39                                      )
    DECLARE_ENUM_VAL( FPU_FPSCR_VXSNAN_n,   1                                       )
    DECLARE_ENUM_VAL( FPU_FPSCR_VXSNAN_i,   IBM_BIT_INDEX( 64, FPU_FPSCR_VXSNAN_e ) )
    DECLARE_ENUM_VAL( FPU_FPSCR_VXISI_e,    40                                      )
    DECLARE_ENUM_VAL( FPU_FPSCR_VXISI_n,    1                                       )
    DECLARE_ENUM_VAL( FPU_FPSCR_VXISI_i,    IBM_BIT_INDEX( 64, FPU_FPSCR_VXISI_e  ) )
    DECLARE_ENUM_VAL( FPU_FPSCR_VXIDI_e,    41                                      )
    DECLARE_ENUM_VAL( FPU_FPSCR_VXIDI_n,    1                                       )
    DECLARE_ENUM_VAL( FPU_FPSCR_VXIDI_i,    IBM_BIT_INDEX( 64, FPU_FPSCR_VXIDI_e  ) )
    DECLARE_ENUM_VAL( FPU_FPSCR_VXZDZ_e,    42                                      )
    DECLARE_ENUM_VAL( FPU_FPSCR_VXZDZ_n,    1                                       )
    DECLARE_ENUM_VAL( FPU_FPSCR_VXZDZ_i,    IBM_BIT_INDEX( 64, FPU_FPSCR_VXZDZ_e  ) )
    DECLARE_ENUM_VAL( FPU_FPSCR_VXIMZ_e,    43                                      )
    DECLARE_ENUM_VAL( FPU_FPSCR_VXIMZ_n,    1                                       )
    DECLARE_ENUM_VAL( FPU_FPSCR_VXIMZ_i,    IBM_BIT_INDEX( 64, FPU_FPSCR_VXIMZ_e  ) )
    DECLARE_ENUM_VAL( FPU_FPSCR_VXVC_e,     44                                      )
    DECLARE_ENUM_VAL( FPU_FPSCR_VXVC_n,     1                                       )
    DECLARE_ENUM_VAL( FPU_FPSCR_VXVC_i,     IBM_BIT_INDEX( 64, FPU_FPSCR_VXVC_e   ) )
    DECLARE_ENUM_VAL( FPU_FPSCR_FR_e,       45                                      )
    DECLARE_ENUM_VAL( FPU_FPSCR_FR_n,       1                                       )
    DECLARE_ENUM_VAL( FPU_FPSCR_FR_i,       IBM_BIT_INDEX( 64, FPU_FPSCR_FR_e     ) )
    DECLARE_ENUM_VAL( FPU_FPSCR_FI_e,       46                                      )
    DECLARE_ENUM_VAL( FPU_FPSCR_FI_n,        1                                      )
    DECLARE_ENUM_VAL( FPU_FPSCR_FI_i,       IBM_BIT_INDEX( 64, FPU_FPSCR_FI_e     ) )
    DECLARE_ENUM_VAL( FPU_FPSCR_FPRF_e,     47                                      )
    DECLARE_ENUM_VAL( FPU_FPSCR_FPRF_n,     1                                       )
    DECLARE_ENUM_VAL( FPU_FPSCR_FPRF_i,     IBM_BIT_INDEX( 64, FPU_FPSCR_FPRF_e   ) )
    DECLARE_ENUM_VAL( FPU_FPSCR_FL_e,       48                                      )
    DECLARE_ENUM_VAL( FPU_FPSCR_FL_n,       1                                       )
    DECLARE_ENUM_VAL( FPU_FPSCR_FL_i,       IBM_BIT_INDEX( 64, FPU_FPSCR_FL_e     ) )
    DECLARE_ENUM_VAL( FPU_FPSCR_FG_e,       49                                      )
    DECLARE_ENUM_VAL( FPU_FPSCR_FG_n,       1                                       )
    DECLARE_ENUM_VAL( FPU_FPSCR_FG_i,       IBM_BIT_INDEX( 64, FPU_FPSCR_FG_e     ) )
    DECLARE_ENUM_VAL( FPU_FPSCR_FE_e,       50                                      )
    DECLARE_ENUM_VAL( FPU_FPSCR_FE_n,       1                                       )
    DECLARE_ENUM_VAL( FPU_FPSCR_FE_i,       IBM_BIT_INDEX( 64, FPU_FPSCR_FE_e     ) )
    DECLARE_ENUM_VAL( FPU_FPSCR_FU_e,       51                                      )
    DECLARE_ENUM_VAL( FPU_FPSCR_FU_n,       1                                       )
    DECLARE_ENUM_VAL( FPU_FPSCR_FU_i,       IBM_BIT_INDEX( 64, FPU_FPSCR_FU_e     ) )
    DECLARE_ENUM_VAL( FPU_FPSCR_RESERVED_e, 52                                      )
    DECLARE_ENUM_VAL( FPU_FPSCR_RESERVED_n, 1                                       )
    DECLARE_ENUM_VAL( FPU_FPSCR_RESERVED_i, IBM_BIT_INDEX( 64, FPU_FPSCR_RESERVED_e ) )
    DECLARE_ENUM_VAL( FPU_FPSCR_VXSOFT_e,   53                                      )
    DECLARE_ENUM_VAL( FPU_FPSCR_VXSOFT_n,   1                                       )
    DECLARE_ENUM_VAL( FPU_FPSCR_VXSOFT_i,   IBM_BIT_INDEX( 64, FPU_FPSCR_VXSOFT_e ) )
    DECLARE_ENUM_VAL( FPU_FPSCR_VXSQRT_e,   54                                      )
    DECLARE_ENUM_VAL( FPU_FPSCR_VXSQRT_n,   1                                       )
    DECLARE_ENUM_VAL( FPU_FPSCR_VXSQRT_i,   IBM_BIT_INDEX( 64, FPU_FPSCR_VXSQRT_e ) )
    DECLARE_ENUM_VAL( FPU_FPSCR_VXCVI_e,    55                                      )
    DECLARE_ENUM_VAL( FPU_FPSCR_VXCVI_n,    1                                       )
    DECLARE_ENUM_VAL( FPU_FPSCR_VXCVI_i,    IBM_BIT_INDEX( 64, FPU_FPSCR_VXCVI_e  ) )
    DECLARE_ENUM_VAL( FPU_FPSCR_VE_e,       56                                      )
    DECLARE_ENUM_VAL( FPU_FPSCR_VE_n,       1                                       )
    DECLARE_ENUM_VAL( FPU_FPSCR_VE_i,       IBM_BIT_INDEX( 64, FPU_FPSCR_VE_e     ) )
    DECLARE_ENUM_VAL( FPU_FPSCR_OE_e,       57                                      )
    DECLARE_ENUM_VAL( FPU_FPSCR_OE_n,       1                                       )
    DECLARE_ENUM_VAL( FPU_FPSCR_OE_i,       IBM_BIT_INDEX( 64, FPU_FPSCR_OE_e     ) )
    DECLARE_ENUM_VAL( FPU_FPSCR_UE_e,       58                                      )
    DECLARE_ENUM_VAL( FPU_FPSCR_UE_n,       1                                       )
    DECLARE_ENUM_VAL( FPU_FPSCR_UE_i,       IBM_BIT_INDEX( 64, FPU_FPSCR_UE_e     ) )
    DECLARE_ENUM_VAL( FPU_FPSCR_ZE_e,       59                                      )
    DECLARE_ENUM_VAL( FPU_FPSCR_ZE_n,       1                                       )
    DECLARE_ENUM_VAL( FPU_FPSCR_ZE_i,       IBM_BIT_INDEX( 64, FPU_FPSCR_ZE_e     ) )
    DECLARE_ENUM_VAL( FPU_FPSCR_XE_e,       60                                      )
    DECLARE_ENUM_VAL( FPU_FPSCR_XE_n,       1                                      )
    DECLARE_ENUM_VAL( FPU_FPSCR_XE_i,       IBM_BIT_INDEX( 64, FPU_FPSCR_XE_e     ) )
    DECLARE_ENUM_VAL( FPU_FPSCR_NI_e,       61                                      )
    DECLARE_ENUM_VAL( FPU_FPSCR_NI_n,       1                                       )
    DECLARE_ENUM_VAL( FPU_FPSCR_NI_i,       IBM_BIT_INDEX( 64, FPU_FPSCR_NI_e  ) )
    DECLARE_ENUM_VAL( FPU_FPSCR_RN_e,       63                                      )
    DECLARE_ENUM_VAL( FPU_FPSCR_RN_n,       2                                       )
    DECLARE_ENUM_VAL( FPU_FPSCR_RN_i,       IBM_BIT_INDEX( 64, FPU_FPSCR_RN_e     ) )
END_ENUM( FPU_FPSCR_FIELD )

BEGIN_ENUM( FPU_FPSCR_RN )
DECLARE_ENUM_VAL( FPU_FPSCR_RN_NEAR,      0b00 )
DECLARE_ENUM_VAL( FPU_FPSCR_RN_ZERO,      0b01 )
DECLARE_ENUM_VAL( FPU_FPSCR_RN_POSI,      0b10 )
DECLARE_ENUM_VAL( FPU_FPSCR_RN_NEGI,      0b11 )
END_ENUM( FPU_FPSCR_RN )


#endif /* PPC_476FP_FPU_FIELDS_H_ */
