[#rumboot-feat-endian-swap]
==== Исполнение кода вторичного загрузчика в little endian режиме

Процессорное ядро PowerPC поддерживает работу как в режиме big endian, так и в режиме little endian. Режим big endian является основным, и в этом режиме работает начальный загрузчик. 

Начальный загрузчик поддерживает загрузку и исполнение кода, скомпилированного в режиме little endian. Порядок байт определеяется по порядку байт поля magic заголовка загружаемого образа. 

В случае, если загрузчик получил образ собранный как little endian, загрузчик перенастраивает страницы TLB для доступа к памятям IM0, IM1, IM2, IM3 в режим little endian. После завершения работы программы при возврате в bootrom выполняется обратная операция. 

Если программа загружается или использует какие-то другие памяти, отличные от вышеуказанных, то пользователю необходимо самостоятельно произвести настройку TLB соответствующим образом. 

[#rumboot-feat-nmrisc]

Загрузчик в составе микросхемы поддерживает загрузку двух гетерогренных процессорных ядер. см. Таблицу <<tbl_target_cluster_id>> 

.Возможные значения поля target_cpu_cluster заголовка образа вторичного загрузчика.
[#tbl_target_cluster_id,cols="10,10,80",options="header"]
|===
|Имя процессора
|target_cpu_cluster
|Описание

|PowerPC
|0
|Основное процессорное ядро

|NMRISC
|1
|Вспомогательное RISC ядро
|===

Загрузка вспомогательного процессорного ядра NMRISC возможна только с использованием третьей версии заголовка вторичного загрузчика.

В синхронном режиме исполнения начальный загрузчик получает отладочный вывод и признак завершения работы программы от вспомогатльного ядра через аппаратуру APB FIFO и выводит на в UART. В асинхронном режиме исполнения опрос APB FIFO не производится.