#include <basis/defs.h>

/* --- SCTL --- */

#define rgSCTL_PCIE_RST   (*(volatile int*)(SCTL_BASE + SCTL_PCIE_RST  ))
#define rgSCTL_PCIE_REG_0 (*(volatile int*)(SCTL_BASE + SCTL_PCIE_REG_0))
#define rgSCTL_PCIE_REG_1 (*(volatile int*)(SCTL_BASE + SCTL_PCIE_REG_1))
#define rgSCTL_PCIE_REG_2 (*(volatile int*)(SCTL_BASE + SCTL_PCIE_REG_2))

/* --- PCIe_Phy --- */
    // paddr [11] was excluded, so it paddr forms next way
#define rgPCIe_Phy_PCS_CMN_CTRL1             (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PCS_CMN_CTRL1          ))
#define rgPCIe_Phy_PCS_CMN_CTRL2             (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PCS_CMN_CTRL2          ))
#define rgPCIe_Phy_PCS_COM_LOCK_CFG1         (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PCS_COM_LOCK_CFG1      ))
#define rgPCIe_Phy_PCS_COM_LOCK_CFG2         (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PCS_COM_LOCK_CFG2      ))
#define rgPCIe_Phy_PCS_GEN3_EIE_LOCK_CFG     (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PCS_GEN3_EIE_LOCK_CFG  ))
#define rgPCIe_Phy_PCS_LANE_DSBL             (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PCS_LANE_DSBL          ))
#define rgPCIe_Phy_PCS_RCV_DET_INH           (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PCS_RCV_DET_INH        ))
#define rgPCIe_Phy_PCS_ISO_CMN_CTRL          (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PCS_ISO_CMN_CTRL       ))
#define rgPCIe_Phy_EQ_TRAIN_CTRL             (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_EQ_TRAIN_CTRL          ))
#define rgPCIe_Phy_ISO_LN_CTRL               (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_ISO_LN_CTRL            ))
#define rgPCIe_Phy_EQ_COEF_TRAIN_CTRL        (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_EQ_COEF_TRAIN_CTRL     ))
#define rgPCIe_Phy_PCS_ISO_TX_CTRL           (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PCS_ISO_TX_CTRL        ))
#define rgPCIe_Phy_PCS_ISO_TX_LPC_LO         (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PCS_ISO_TX_LPC_LO      ))
#define rgPCIe_Phy_PCS_ISO_TX_LPC_HI         (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PCS_ISO_TX_LPC_HI      ))
#define rgPCIe_Phy_PCS_ISO_TX_DMPH_LO        (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PCS_ISO_TX_DMPH_LO     ))
#define rgPCIe_Phy_PCS_ISO_TX_DMPH_HI        (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PCS_ISO_TX_DMPH_HI     ))
#define rgPCIe_Phy_PCS_ISO_TX_FSLF           (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PCS_ISO_TX_FSLF        ))
#define rgPCIe_Phy_PCS_ISO_TX_DATA_LO        (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PCS_ISO_TX_DATA_LO     ))
#define rgPCIe_Phy_PCS_ISO_TX_DATA_HI        (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PCS_ISO_TX_DATA_HI     ))
#define rgPCIe_Phy_PCS_ISO_RX_CTRL           (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PCS_ISO_RX_CTRL        ))
#define rgPCIe_Phy_PCS_ISO_RX_EQ_EVAL        (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PCS_ISO_RX_EQ_EVAL     ))
#define rgPCIe_Phy_PCS_ISO_RX_DATA_LO        (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PCS_ISO_RX_DATA_LO     ))
#define rgPCIe_Phy_PCS_ISO_RX_DATA_HI        (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PCS_ISO_RX_DATA_HI     ))
#define rgPCIe_Phy_PMA_CMN_CTRL              (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_CTRL           ))
#define rgPCIe_Phy_PMA_SSM_STATE             (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_SSM_STATE          ))
#define rgPCIe_Phy_PMA_PSM_STATE_LO          (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_PSM_STATE_LO       ))
#define rgPCIe_Phy_PMA_PSM_STATE_HI          (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_PSM_STATE_HI       ))
#define rgPCIe_Phy_PMA_ISO_CMN_CTRL          (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_ISO_CMN_CTRL       ))
#define rgPCIe_Phy_PMA_ISO_MODE              (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_ISO_MODE           ))
#define rgPCIe_Phy_PMA_ISO_PWRST_CTRL        (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_ISO_PWRST_CTRL     ))
#define rgPCIe_Phy_PMA_ISOLATION_CTRL        (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_ISOLATION_CTRL     ))
#define rgPCIe_Phy_PMA_PMA_CMN_SSM_DIAG      (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_PMA_CMN_SSM_DIAG   ))
#define rgPCIe_Phy_PMA_XCVR_CTRL             (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_XCVR_CTRL          ))
#define rgPCIe_Phy_PMA_XCVR_LPBK             (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_XCVR_LPBK          ))
#define rgPCIe_Phy_PMA_PI_POS                (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_PI_POS             ))
#define rgPCIe_Phy_PMA_ISO_XCVR_CTRL         (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_ISO_XCVR_CTRL      ))
#define rgPCIe_Phy_PMA_ISO_TX_LPC_LO         (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_ISO_TX_LPC_LO      ))
#define rgPCIe_Phy_PMA_ISO_TX_LPC_HI         (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_ISO_TX_LPC_HI      ))
#define rgPCIe_Phy_PMA_ISO_TX_DMPH_LO        (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_ISO_TX_DMPH_LO     ))
#define rgPCIe_Phy_PMA_ISO_TX_DMPH_HI        (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_ISO_TX_DMPH_HI     ))
#define rgPCIe_Phy_PMA_ISO_TX_FSLF           (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_ISO_TX_FSLF        ))
#define rgPCIe_Phy_PMA_ISO_TX_MGN            (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_ISO_TX_MGN         ))
#define rgPCIe_Phy_PMA_ISO_RX_EQ_CTRL        (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_ISO_RX_EQ_CTRL     ))
#define rgPCIe_Phy_PMA_ISO_DATA_LO           (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_ISO_DATA_LO        ))
#define rgPCIe_Phy_PMA_ISO_DATA_HI           (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_ISO_DATA_HI        ))
#define rgPCIe_Phy_PMA_TX_BIST_CTRL          (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_TX_BIST_CTRL       ))
#define rgPCIe_Phy_PMA_TX_BIST_UDDWR         (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_TX_BIST_UDDWR      ))
#define rgPCIe_Phy_PMA_RX_BIST_CTRL          (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_RX_BIST_CTRL       ))
#define rgPCIe_Phy_PMA_RX_BIST_SYNCCNT       (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_RX_BIST_SYNCCNT    ))
#define rgPCIe_Phy_PMA_RX_BIST_UDDWR         (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_RX_BIST_UDDWR      ))
#define rgPCIe_Phy_PMA_RX_BIST_ERRCNT        (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_RX_BIST_ERRCNT     ))
#define rgPCIe_Phy_PMA_CMN_PID_TYPE          (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_PID_TYPE       ))
#define rgPCIe_Phy_PMA_CMN_PID_NUM           (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_PID_NUM        ))
#define rgPCIe_Phy_PMA_CMN_PID_REV           (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_PID_REV        ))
#define rgPCIe_Phy_PMA_CMN_PID_MFG           (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_PID_MFG        ))
#define rgPCIe_Phy_PMA_CMN_PID_NODE          (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_PID_NODE       ))
#define rgPCIe_Phy_PMA_CMN_PID_FLV           (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_PID_FLV        ))
#define rgPCIe_Phy_PMA_CMN_PID_IOV           (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_PID_IOV        ))
#define rgPCIe_Phy_PMA_CMN_PID_METAL         (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_PID_METAL      ))
#define rgPCIe_Phy_PMA_CMN_PID_LANES         (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_PID_LANES      ))
#define rgPCIe_Phy_RX_EYESURF_CTRL           (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_RX_EYESURF_CTRL        ))
#define rgPCIe_Phy_RX_EYESURF_TMR_DELLOW     (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_RX_EYESURF_TMR_DELLOW  ))
#define rgPCIe_Phy_RX_EYESURF_TMR_DELHIGH    (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_RX_EYESURF_TMR_DELHIGH ))
#define rgPCIe_Phy_RX_EYESURF_TMR_TESTLOW    (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_RX_EYESURF_TMR_TESTLOW ))
#define rgPCIe_Phy_RX_EYESURF_TMR_TESTHIGH   (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_RX_EYESURF_TMR_TESTHIGH))
#define rgPCIe_Phy_RX_EYESURF_NS_COORD       (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_RX_EYESURF_NS_COORD    ))
#define rgPCIe_Phy_RX_EYESURF_EW_COORD       (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_RX_EYESURF_EW_COORD    ))
#define rgPCIe_Phy_RX_EYESURF_ERRCNT         (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_RX_EYESURF_ERRCNT      ))

/* --- This registers are used for netlist simspeedup --- */
#define rgPCIe_Phy_MASSWR_TX_RCVDET_CTRL                    (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_MASSWR_TX_RCVDET_CTRL                ))
#define rgPCIe_Phy_CMN_SSM_BANDGAP_TMR                      (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_CMN_SSM_BANDGAP_TMR                  ))
#define rgPCIe_Phy_CMN_SSM_BIAS_TMR                         (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_CMN_SSM_BIAS_TMR                     ))
#define rgPCIe_Phy_CMN_SSM_PLLEN_TMR                        (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_CMN_SSM_PLLEN_TMR                    ))
#define rgPCIe_Phy_CMN_SSM_PLLPRE_TMR                       (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_CMN_SSM_PLLPRE_TMR                   ))
#define rgPCIe_Phy_CMN_SSM_PLLVREF_TMR                      (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_CMN_SSM_PLLVREF_TMR                  ))
#define rgPCIe_Phy_CMN_SSM_PLLLOCK_TMR                      (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_CMN_SSM_PLLLOCK_TMR                  ))
#define rgPCIe_Phy_CMN_SSM_PLLCLKDIS_TMR                    (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_CMN_SSM_PLLCLKDIS_TMR                ))
#define rgPCIe_Phy_CMN_SSM_LANECAL_TMR                      (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_CMN_SSM_LANECAL_TMR                  ))
#define rgPCIe_Phy_CMN_SSM_A0IN_TMR                         (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_CMN_SSM_A0IN_TMR                     ))
#define rgPCIe_Phy_CMN_SSM_A1IN_TMR                         (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_CMN_SSM_A1IN_TMR                     ))
#define rgPCIe_Phy_CMN_SSM_A2IN_TMR                         (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_CMN_SSM_A2IN_TMR                     ))
#define rgPCIe_Phy_CMN_SSM_A3IN_TMR                         (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_CMN_SSM_A3IN_TMR                     ))
#define rgPCIe_Phy_CMN_BGCAL_OVRD                           (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_CMN_BGCAL_OVRD                       ))
#define rgPCIe_Phy_CMN_PLL_CPI_OVRD                         (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_CMN_PLL_CPI_OVRD                     ))
#define rgPCIe_Phy_MASSWR_CMN_SDCAL0_OVRD                   (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_MASSWR_CMN_SDCAL0_OVRD               ))
#define rgPCIe_Phy_MASSWR_CMN_SDCAL1_OVRD                   (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_MASSWR_CMN_SDCAL1_OVRD               ))
#define rgPCIe_Phy_CMN_PLL_VCOCAL_OVRD                      (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_CMN_PLL_VCOCAL_OVRD                  ))
#define rgPCIe_Phy_CMN_PLL_VCOCAL_CNT_START                 (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_CMN_PLL_VCOCAL_CNT_START             ))
#define rgPCIe_Phy_CMN_PLL_LOCK_CNT_START                   (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_CMN_PLL_LOCK_CNT_START               ))
#define rgPCIe_Phy_MASSWR_RX_IQPI_ILL_CAL_OVRD              (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_MASSWR_RX_IQPI_ILL_CAL_OVRD          ))
#define rgPCIe_Phy_MASSWR_RX_IQPI_ILL_LOCK_REFCNT_START     (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_MASSWR_RX_IQPI_ILL_LOCK_REFCNT_START ))
#define rgPCIe_Phy_MASSWR_RX_IQPI_ILL_LOCK_CALCNT_START0    (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_MASSWR_RX_IQPI_ILL_LOCK_CALCNT_START0))
#define rgPCIe_Phy_MASSWR_RX_IQPI_ILL_LOCK_CALCNT_START1    (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_MASSWR_RX_IQPI_ILL_LOCK_CALCNT_START1))
#define rgPCIe_Phy_MASSWR_RX_EPI_ILL_CAL_OVRD               (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_MASSWR_RX_EPI_ILL_CAL_OVRD           ))
#define rgPCIe_Phy_MASSWR_RX_EPI_ILL_LOCK_REFCNT_START      (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_MASSWR_RX_EPI_ILL_LOCK_REFCNT_START  ))
#define rgPCIe_Phy_MASSWR_RX_EPI_ILL_LOCK_CALCNT_START0     (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_MASSWR_RX_EPI_ILL_LOCK_CALCNT_START0 ))
#define rgPCIe_Phy_MASSWR_RX_EPI_ILL_LOCK_CALCNT_START1     (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_MASSWR_RX_EPI_ILL_LOCK_CALCNT_START1 ))
// #define rgPCIe_Phy_LANE_CAL_RESET_TIME_VALUE                (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_LANE_CAL_RESET_TIME_VALUE            ))  register wasn`t found */
#define rgPCIe_Phy_CMN_TXPUCAL_OVRD                         (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_CMN_TXPUCAL_OVRD                     ))
#define rgPCIe_Phy_CMN_TXPDCAL_OVRD                         (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_CMN_TXPDCAL_OVRD                     ))
#define rgPCIe_Phy_CMN_RXCAL_OVRD                           (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_CMN_RXCAL_OVRD                       ))
#define rgPCIe_Phy_MASSWR_RX_SLC_INIT_TMR                   (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_MASSWR_RX_SLC_INIT_TMR               ))
#define rgPCIe_Phy_MASSWR_RX_SLC_RUN_TMR                    (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_MASSWR_RX_SLC_RUN_TMR                ))
// #define rgPCIe_Phy_CMN_PRPLL_LOCK_CNT_START                 (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_CMN_PRPLL_LOCK_CNT_START             ))  register wasn`t found */

#define rgPCIe_Phy_PMA_CMN_PID_TYPE                     (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_PID_TYPE                         ))
#define rgPCIe_Phy_PMA_CMN_PID_NUM                      (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_PID_NUM                          ))
#define rgPCIe_Phy_PMA_CMN_PID_REV                      (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_PID_REV                          ))
#define rgPCIe_Phy_PMA_CMN_PID_MFG                      (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_PID_MFG                          ))
#define rgPCIe_Phy_PMA_CMN_PID_NODE                     (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_PID_NODE                         ))
#define rgPCIe_Phy_PMA_CMN_PID_FLV                      (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_PID_FLV                          ))
#define rgPCIe_Phy_PMA_CMN_PID_IOV                      (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_PID_IOV                          ))
#define rgPCIe_Phy_PMA_CMN_PID_METAL                    (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_PID_METAL                        ))
#define rgPCIe_Phy_PMA_CMN_PID_LANES                    (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_PID_LANES                        ))
#define rgPCIe_Phy_PMA_CMN_SSM_BANDGAP_TMR              (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_SSM_BANDGAP_TMR                  ))
#define rgPCIe_Phy_PMA_CMN_SSM_BIAS_TMR                 (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_SSM_BIAS_TMR                     ))
#define rgPCIe_Phy_PMA_CMN_SSM_PLLEN_TMR                (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_SSM_PLLEN_TMR                    ))
#define rgPCIe_Phy_PMA_CMN_SSM_PLLVREF_TMR              (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_SSM_PLLVREF_TMR                  ))
#define rgPCIe_Phy_PMA_CMN_SSM_LANECAL_TMR              (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_SSM_LANECAL_TMR                  ))
#define rgPCIe_Phy_PMA_CMN_SSM_A1OUT_TMR                (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_SSM_A1OUT_TMR                    ))
#define rgPCIe_Phy_PMA_CMN_PSC_A0                       (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_PSC_A0                           ))
#define rgPCIe_Phy_PMA_CMN_PSC_A1                       (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_PSC_A1                           ))
#define rgPCIe_Phy_PMA_CMN_PSC_A2                       (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_PSC_A2                           ))
#define rgPCIe_Phy_PMA_CMN_PSC_A4                       (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_PSC_A4                           ))
#define rgPCIe_Phy_PMA_CMN_PLLCPICAL_CTRL               (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_PLLCPICAL_CTRL                   ))
#define rgPCIe_Phy_PMA_CMN_PLLCPICAL_OVRD               (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_PLLCPICAL_OVRD                   ))
#define rgPCIe_Phy_PMA_CMN_PLLCPICAL_INIT_TMR           (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_PLLCPICAL_INIT_TMR               ))
#define rgPCIe_Phy_PMA_CMN_RXCAL_CTRL                   (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_RXCAL_CTRL                       ))
#define rgPCIe_Phy_PMA_CMN_RXCAL_OVRD                   (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_RXCAL_OVRD                       ))
#define rgPCIe_Phy_PMA_CMN_RXCAL_INIT_TMR               (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_RXCAL_INIT_TMR                   ))
#define rgPCIe_Phy_PMA_CMN_TXPUCAL_CTRL                 (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_TXPUCAL_CTRL                     ))
#define rgPCIe_Phy_PMA_CMN_TXPUCAL_OVRD                 (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_TXPUCAL_OVRD                     ))
#define rgPCIe_Phy_PMA_CMN_TXPUCAL_INIT_TMR             (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_TXPUCAL_INIT_TMR                 ))
#define rgPCIe_Phy_PMA_CMN_TXPDCAL_CTRL                 (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_TXPDCAL_CTRL                     ))
#define rgPCIe_Phy_PMA_CMN_TXPDCAL_OVRD                 (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_TXPDCAL_OVRD                     ))
#define rgPCIe_Phy_PMA_CMN_TXPDCAL_INIT_TMR             (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_CMN_TXPDCAL_INIT_TMR                 ))
#define rgPCIe_Phy_PMA_TX_HBDC_PRE_OVRD                 (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_TX_HBDC_PRE_OVRD                     ))
#define rgPCIe_Phy_PMA_TX_HBDC_MAIN_OVRD                (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_TX_HBDC_MAIN_OVRD                    ))
#define rgPCIe_Phy_PMA_TX_HBDC_POST_OVRD                (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_TX_HBDC_POST_OVRD                    ))
#define rgPCIe_Phy_PMA_TX_HBDC_PRE_PREM_OVRD            (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_TX_HBDC_PRE_PREM_OVRD                ))
#define rgPCIe_Phy_PMA_TX_HBDC_MAIN_INITM_OVRD          (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_TX_HBDC_MAIN_INITM_OVRD              ))
#define rgPCIe_Phy_PMA_TX_RCVDET_CTRL                   (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_TX_RCVDET_CTRL                       ))
#define rgPCIe_Phy_PMA_TX_BIST_CTRL                     (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_TX_BIST_CTRL                         ))
#define rgPCIe_Phy_PMA_TX_BIST_UDDWR                    (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_TX_BIST_UDDWR                        ))
#define rgPCIe_Phy_PMA_RX_IQPI_ILL_CAL_CTRL             (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_RX_IQPI_ILL_CAL_CTRL                 ))
#define rgPCIe_Phy_PMA_RX_IQPI_ILL_CAL_START            (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_RX_IQPI_ILL_CAL_START                ))
#define rgPCIe_Phy_PMA_RX_IQPI_ILL_CAL_INIT_TMR         (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_RX_IQPI_ILL_CAL_INIT_TMR             ))
#define rgPCIe_Phy_PMA_RX_IQPI_ILL_CAL_ITER_TMR         (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_RX_IQPI_ILL_CAL_ITER_TMR             ))
#define rgPCIe_Phy_PMA_RX_IQPI_ILL_LOCK_CALCNT_START0   (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_RX_IQPI_ILL_LOCK_CALCNT_START0       ))
#define rgPCIe_Phy_PMA_RX_EPI_ILL_CAL_CTRL              (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_RX_EPI_ILL_CAL_CTRL                  ))
#define rgPCIe_Phy_PMA_RX_EPI_ILL_CAL_START             (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_RX_EPI_ILL_CAL_START                 ))
#define rgPCIe_Phy_PMA_RX_EPI_ILL_CAL_INIT_TMR          (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_RX_EPI_ILL_CAL_INIT_TMR              ))
#define rgPCIe_Phy_PMA_RX_EPI_ILL_CAL_ITER_TMR          (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_RX_EPI_ILL_CAL_ITER_TMR              ))
#define rgPCIe_Phy_PMA_RX_EPI_ILL_LOCK_CALCNT_START0    (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_RX_EPI_ILL_LOCK_CALCNT_START0        ))
#define rgPCIe_Phy_PMA_RX_CDRLF_CNFG                    (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_RX_CDRLF_CNFG                        ))
#define rgPCIe_Phy_PMA_RX_CDRLF_CNFG2                   (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_RX_CDRLF_CNFG2                       ))
#define rgPCIe_Phy_PMA_RX_CDRLF_MGN_DIAG                (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_RX_CDRLF_MGN_DIAG                    ))
#define rgPCIe_Phy_PMA_RX_SIGDET_FILT_TMR               (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_RX_SIGDET_FILT_TMR                   ))
#define rgPCIe_Phy_PMA_RX_SIGDET_DLY_TMR                (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_RX_SIGDET_DLY_TMR                    ))
#define rgPCIe_Phy_PMA_RX_SIGDET_MIN_TMR                (*(volatile int*)(PCIE_PHY_BASE + PCIe_Phy_PMA_RX_SIGDET_MIN_TMR                    ))


/* --- PCIe --- */
#define rgPCIe_EP_i_vendor_id_device_id                    (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_vendor_id_device_id            ))
#define rgPCIe_EP_i_command_status                         (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_command_status                 ))
#define rgPCIe_EP_i_revision_id_class_code                 (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_revision_id_class_code         ))
#define rgPCIe_EP_i_bist_header_latency_cache_line         (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_bist_header_latency_cache_line ))
#define rgPCIe_EP_i_base_addr_0                            (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_base_addr_0                    ))
#define rgPCIe_EP_i_base_addr_1                            (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_base_addr_1                    ))
#define rgPCIe_EP_i_base_addr_2                            (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_base_addr_2                    ))
#define rgPCIe_EP_i_base_addr_3                            (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_base_addr_3                    ))
#define rgPCIe_EP_i_base_addr_4                            (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_base_addr_4                    ))
#define rgPCIe_EP_i_base_addr_5                            (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_base_addr_5                    ))
#define rgPCIe_EP_i_subsystem_vendor_id_subsystem_i        (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_subsystem_vendor_id_subsystem_i))
#define rgPCIe_EP_i_capabilities_pointer                   (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_capabilities_pointer           ))
#define rgPCIe_EP_i_intrpt_line_intrpt_pin                 (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_intrpt_line_intrpt_pin         ))
#define rgPCIe_EP_i_pwr_mgmt_cap                           (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_pwr_mgmt_cap                   ))
#define rgPCIe_EP_i_pwr_mgmt_ctrl_stat_rep                 (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_pwr_mgmt_ctrl_stat_rep         ))
#define rgPCIe_EP_i_msi_ctrl_reg                           (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_msi_ctrl_reg                   ))
#define rgPCIe_EP_i_msi_msg_low_addr                       (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_msi_msg_low_addr               ))
#define rgPCIe_EP_i_msi_msg_hi_addr                        (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_msi_msg_hi_addr                ))
#define rgPCIe_EP_i_msi_msg_data                           (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_msi_msg_data                   ))
#define rgPCIe_EP_i_msi_mask                               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_msi_mask                       ))
#define rgPCIe_EP_i_msi_pending_bits                       (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_msi_pending_bits               ))
#define rgPCIe_EP_i_msix_ctrl                              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_msix_ctrl                      ))
#define rgPCIe_EP_i_msix_tbl_offset                        (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_msix_tbl_offset                ))
#define rgPCIe_EP_i_msix_pending_intrpt                    (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_msix_pending_intrpt            ))
#define rgPCIe_EP_i_pcie_cap_list                          (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_pcie_cap_list                  ))
#define rgPCIe_EP_i_pcie_dev_cap                           (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_pcie_dev_cap                   ))
#define rgPCIe_EP_i_pcie_dev_ctrl_status                   (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_pcie_dev_ctrl_status           ))
#define rgPCIe_EP_i_link_cap                               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_link_cap                       ))
#define rgPCIe_EP_i_link_ctrl_status                       (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_link_ctrl_status               ))
#define rgPCIe_EP_i_pcie_dev_cap_2                         (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_pcie_dev_cap_2                 ))
#define rgPCIe_EP_i_pcie_dev_ctrl_status_2                 (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_pcie_dev_ctrl_status_2         ))
#define rgPCIe_EP_i_link_cap_2_reg                         (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_link_cap_2_reg                 ))
#define rgPCIe_EP_i_link_ctrl_status_2                     (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_link_ctrl_status_2             ))
#define rgPCIe_EP_i_AER_enhanced_cap_hdr                   (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_AER_enhanced_cap_hdr           ))
#define rgPCIe_EP_i_uncorr_err_status                      (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_uncorr_err_status              ))
#define rgPCIe_EP_i_uncorr_err_mask                        (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_uncorr_err_mask                ))
#define rgPCIe_EP_i_uncorr_err_severity                    (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_uncorr_err_severity            ))
#define rgPCIe_EP_i_corr_err_status                        (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_corr_err_status                ))
#define rgPCIe_EP_i_corr_err_mask                          (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_corr_err_mask                  ))
#define rgPCIe_EP_i_advcd_err_cap_ctrl                     (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_advcd_err_cap_ctrl             ))
#define rgPCIe_EP_i_hdr_log_0                              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_hdr_log_0                      ))
#define rgPCIe_EP_i_hdr_log_1                              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_hdr_log_1                      ))
#define rgPCIe_EP_i_hdr_log_2                              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_hdr_log_2                      ))
#define rgPCIe_EP_i_hdr_log_3                              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_EP_i_hdr_log_3                      ))

#define rgPCIe_RP_i_vendor_id_device_id                    (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_vendor_id_device_id            ))
#define rgPCIe_RP_i_command_status                         (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_command_status                 ))
#define rgPCIe_RP_i_revision_id_class_code                 (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_revision_id_class_code         ))
#define rgPCIe_RP_i_bist_header_latency_cache_line         (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_bist_header_latency_cache_line ))
#define rgPCIe_RP_i_RC_BAR_0                               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_RC_BAR_0                       ))
#define rgPCIe_RP_i_RC_BAR_1                               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_RC_BAR_1                       ))
#define rgPCIe_RP_i_pcie_bus_numbers                       (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_pcie_bus_numbers               ))
#define rgPCIe_RP_i_pcie_io_base_limit                     (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_pcie_io_base_limit             ))
#define rgPCIe_RP_i_pcie_mem_base_limit                    (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_pcie_mem_base_limit            ))
#define rgPCIe_RP_i_pcie_prefetch_base_limit               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_pcie_prefetch_base_limit       ))
#define rgPCIe_RP_i_pcie_prefetch_base_upper               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_pcie_prefetch_base_upper       ))
#define rgPCIe_RP_i_pcie_prefetch_limit_upper              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_pcie_prefetch_limit_upper      ))
#define rgPCIe_RP_i_pcie_io_base_limit_upper               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_pcie_io_base_limit_upper       ))
#define rgPCIe_RP_i_capabilities_pointer                   (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_capabilities_pointer           ))
#define rgPCIe_RP_i_intrpt_line_intrpt_pin                 (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_intrpt_line_intrpt_pin         ))
#define rgPCIe_RP_i_pwr_mgmt_cap                           (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_pwr_mgmt_cap                   ))
#define rgPCIe_RP_i_pwr_mgmt_ctrl_stat_rep                 (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_pwr_mgmt_ctrl_stat_rep         ))
#define rgPCIe_RP_i_msi_ctrl_reg                           (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_msi_ctrl_reg                   ))
#define rgPCIe_RP_i_msi_msg_low_addr                       (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_msi_msg_low_addr               ))
#define rgPCIe_RP_i_msi_msg_hi_addr                        (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_msi_msg_hi_addr                ))
#define rgPCIe_RP_i_msi_msg_data                           (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_msi_msg_data                   ))
#define rgPCIe_RP_i_msi_mask                               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_msi_mask                       ))
#define rgPCIe_RP_i_msi_pending_bits                       (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_msi_pending_bits               ))
#define rgPCIe_RP_i_msix_ctrl                              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_msix_ctrl                      ))
#define rgPCIe_RP_i_msix_tbl_offset                        (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_msix_tbl_offset                ))
#define rgPCIe_RP_i_msix_pending_intrpt                    (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_msix_pending_intrpt            ))
#define rgPCIe_RP_i_pcie_cap_list                          (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_pcie_cap_list                  ))
#define rgPCIe_RP_i_pcie_cap                               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_pcie_cap                       ))
#define rgPCIe_RP_i_pcie_dev_ctrl_status                   (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_pcie_dev_ctrl_status           ))
#define rgPCIe_RP_i_link_cap                               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_link_cap                       ))
#define rgPCIe_RP_i_link_ctrl_status                       (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_link_ctrl_status               ))
#define rgPCIe_RP_i_slot_ctrl_status                       (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_slot_ctrl_status               ))
#define rgPCIe_RP_i_root_ctrl_cap                          (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_root_ctrl_cap                  ))
#define rgPCIe_RP_i_root_status                            (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_root_status                    ))
#define rgPCIe_RP_i_pcie_cap_2                             (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_pcie_cap_2                     ))
#define rgPCIe_RP_i_pcie_dev_ctrl_status_2                 (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_pcie_dev_ctrl_status_2         ))
#define rgPCIe_RP_i_link_cap_2                             (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_link_cap_2                     ))
#define rgPCIe_RP_i_link_ctrl_status_2                     (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_link_ctrl_status_2             ))
#define rgPCIe_RP_i_AER_enhncd_cap                         (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_AER_enhncd_cap                 ))
#define rgPCIe_RP_i_uncorr_err_status                      (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_uncorr_err_status              ))
#define rgPCIe_RP_i_uncorr_err_mask                        (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_uncorr_err_mask                ))
#define rgPCIe_RP_i_uncorr_err_severity                    (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_uncorr_err_severity            ))
#define rgPCIe_RP_i_corr_err_status                        (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_corr_err_status                ))
#define rgPCIe_RP_i_corr_err_mask                          (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_corr_err_mask                  ))
#define rgPCIe_RP_i_adv_err_cap_ctl                        (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_adv_err_cap_ctl                ))
#define rgPCIe_RP_i_hdr_log_0                              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_hdr_log_0                      ))
#define rgPCIe_RP_i_hdr_log_1                              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_hdr_log_1                      ))
#define rgPCIe_RP_i_hdr_log_2                              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_hdr_log_2                      ))
#define rgPCIe_RP_i_hdr_log_3                              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_hdr_log_3                      ))
#define rgPCIe_RP_i_root_err_cmd                           (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_root_err_cmd                   ))
#define rgPCIe_RP_i_root_err_stat                          (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_root_err_stat                  ))
#define rgPCIe_RP_i_err_src_id                             (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_FuncRPConfig + PCIe_RP_i_err_src_id                     ))

#define rgPCIe_LocMgmt_i_pl_config_0_reg                         (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_pl_config_0_reg                     )) 
#define rgPCIe_LocMgmt_i_pl_config_1_reg                         (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_pl_config_1_reg                     )) 
#define rgPCIe_LocMgmt_i_dll_tmr_config_reg                      (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_dll_tmr_config_reg                  )) 
#define rgPCIe_LocMgmt_i_rcv_cred_lim_0_reg                      (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_rcv_cred_lim_0_reg                  )) 
#define rgPCIe_LocMgmt_i_rcv_cred_lim_1_reg                      (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_rcv_cred_lim_1_reg                  )) 
#define rgPCIe_LocMgmt_i_transm_cred_lim_0_reg                   (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_transm_cred_lim_0_reg               )) 
#define rgPCIe_LocMgmt_i_transm_cred_lim_1_reg                   (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_transm_cred_lim_1_reg               )) 
#define rgPCIe_LocMgmt_i_transm_cred_update_int_config_0_reg     (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_transm_cred_update_int_config_0_reg )) 
#define rgPCIe_LocMgmt_i_transm_cred_update_int_config_1_reg     (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_transm_cred_update_int_config_1_reg )) 
#define rgPCIe_LocMgmt_i_L0S_timeout_limit_reg                   (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_L0S_timeout_limit_reg               )) 
#define rgPCIe_LocMgmt_i_transmit_tlp_count_reg                  (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_transmit_tlp_count_reg              )) 
#define rgPCIe_LocMgmt_i_transmit_tlp_payload_dword_count_reg    (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_transmit_tlp_payload_dword_count_reg)) 
#define rgPCIe_LocMgmt_i_receive_tlp_count_reg                   (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_receive_tlp_count_reg               )) 
#define rgPCIe_LocMgmt_i_receive_tlp_payload_dword_count_reg     (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_receive_tlp_payload_dword_count_reg )) 
#define rgPCIe_LocMgmt_i_compln_tmout_lim_0_reg                  (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_compln_tmout_lim_0_reg              )) 
#define rgPCIe_LocMgmt_i_compln_tmout_lim_1_reg                  (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_compln_tmout_lim_1_reg              )) 
#define rgPCIe_LocMgmt_i_L1_st_reentry_delay_reg                 (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_L1_st_reentry_delay_reg             )) 
#define rgPCIe_LocMgmt_i_vendor_id_reg                           (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_vendor_id_reg                       )) 
#define rgPCIe_LocMgmt_i_aspm_L1_entry_tmout_delay_reg           (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_aspm_L1_entry_tmout_delay_reg       )) 
#define rgPCIe_LocMgmt_i_pme_turnoff_ack_delay_reg               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_pme_turnoff_ack_delay_reg           )) 
#define rgPCIe_LocMgmt_i_linkwidth_control_reg                   (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_linkwidth_control_reg               )) 
#define rgPCIe_LocMgmt_i_sris_control_reg                        (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_sris_control_reg                    )) 
#define rgPCIe_LocMgmt_i_shdw_hdr_log_0_reg                      (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_shdw_hdr_log_0_reg                  )) 
#define rgPCIe_LocMgmt_i_shdw_hdr_log_1_reg                      (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_shdw_hdr_log_1_reg                  )) 
#define rgPCIe_LocMgmt_i_shdw_hdr_log_2_reg                      (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_shdw_hdr_log_2_reg                  )) 
#define rgPCIe_LocMgmt_i_shdw_hdr_log_3_reg                      (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_shdw_hdr_log_3_reg                  )) 
#define rgPCIe_LocMgmt_i_shdw_func_num_reg                       (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_shdw_func_num_reg                   )) 
#define rgPCIe_LocMgmt_i_shdw_ur_err_reg                         (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_shdw_ur_err_reg                     )) 
#define rgPCIe_LocMgmt_i_debug_dllp_count_gen1_reg               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_debug_dllp_count_gen1_reg           )) 
#define rgPCIe_LocMgmt_i_debug_dllp_count_gen2_reg               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_debug_dllp_count_gen2_reg           )) 
#define rgPCIe_LocMgmt_i_debug_dllp_count_gen3_reg               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_debug_dllp_count_gen3_reg           )) 
#define rgPCIe_LocMgmt_i_negotiated_lane_map_reg                 (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_negotiated_lane_map_reg             )) 
#define rgPCIe_LocMgmt_i_receive_fts_count_reg                   (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_receive_fts_count_reg               )) 
#define rgPCIe_LocMgmt_i_debug_mux_control_reg                   (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_debug_mux_control_reg               )) 
#define rgPCIe_LocMgmt_i_local_error_status_register             (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_local_error_status_register         )) 
#define rgPCIe_LocMgmt_i_local_intrpt_mask_reg                   (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_local_intrpt_mask_reg               )) 
#define rgPCIe_LocMgmt_i_lcrc_err_count_reg                      (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_lcrc_err_count_reg                  )) 
#define rgPCIe_LocMgmt_i_ecc_corr_err_count_reg                  (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_ecc_corr_err_count_reg              )) 
#define rgPCIe_LocMgmt_i_pme_service_timeout_delay_reg           (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_pme_service_timeout_delay_reg       )) 
#define rgPCIe_LocMgmt_i_root_port_requestor_id_reg              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_root_port_requestor_id_reg          )) 
#define rgPCIe_LocMgmt_i_ep_bus_device_number_reg                (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_ep_bus_device_number_reg            )) 
#define rgPCIe_LocMgmt_i_pf_0_BAR_config_0_reg                   (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_pf_0_BAR_config_0_reg               )) 
#define rgPCIe_LocMgmt_i_pf_0_BAR_config_1_reg                   (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_pf_0_BAR_config_1_reg               )) 
#define rgPCIe_LocMgmt_i_pf_config_reg                           (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_pf_config_reg                       )) 
#define rgPCIe_LocMgmt_i_rc_BAR_config_reg                       (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_rc_BAR_config_reg                   )) 
#define rgPCIe_LocMgmt_i_ecc_corr_err_count_reg_axi              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_ecc_corr_err_count_reg_axi          )) 
#define rgPCIe_LocMgmt_low_power_debug_and_control0              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_low_power_debug_and_control0          ))
#define rgPCIe_LocMgmt_low_power_debug_and_control1              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_low_power_debug_and_control1          ))
#define rgPCIe_LocMgmt_tl_internal_control                       (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_tl_internal_control                   ))
#define rgPCIe_LocMgmt_i_ld_ctrl                                 (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_i_ld_ctrl                             ))
#define rgPCIe_LocMgmt_rx_elec_idle_filter_control               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_LocalMgmt + PCIe_LocMgmt_rx_elec_idle_filter_control           ))

#define rgPCIe_AXI_outregion_0_addr_translation_0                (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_0_addr_translation_0            ))
#define rgPCIe_AXI_outregion_0_addr_translation_1                (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_0_addr_translation_1            ))
#define rgPCIe_AXI_outregion_0_header_descriptor_0               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_0_header_descriptor_0           ))
#define rgPCIe_AXI_outregion_0_header_descriptor_1               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_0_header_descriptor_1           ))
#define rgPCIe_AXI_outregion_0_region_base_addr                  (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_0_region_base_addr              ))
#define rgPCIe_AXI_outregion_1_addr_translation_0                (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_1_addr_translation_0            ))
#define rgPCIe_AXI_outregion_1_addr_translation_1                (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_1_addr_translation_1            ))
#define rgPCIe_AXI_outregion_1_header_descriptor_0               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_1_header_descriptor_0           ))
#define rgPCIe_AXI_outregion_1_header_descriptor_1               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_1_header_descriptor_1           ))
#define rgPCIe_AXI_outregion_1_region_base_addr                  (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_1_region_base_addr              ))
#define rgPCIe_AXI_outregion_2_addr_translation_0                (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_2_addr_translation_0            ))
#define rgPCIe_AXI_outregion_2_addr_translation_1                (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_2_addr_translation_1            ))
#define rgPCIe_AXI_outregion_2_header_descriptor_0               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_2_header_descriptor_0           ))
#define rgPCIe_AXI_outregion_2_header_descriptor_1               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_2_header_descriptor_1           ))
#define rgPCIe_AXI_outregion_2_region_base_addr                  (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_2_region_base_addr              ))
#define rgPCIe_AXI_outregion_3_addr_translation_0                (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_3_addr_translation_0            ))
#define rgPCIe_AXI_outregion_3_addr_translation_1                (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_3_addr_translation_1            ))
#define rgPCIe_AXI_outregion_3_header_descriptor_0               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_3_header_descriptor_0           ))
#define rgPCIe_AXI_outregion_3_header_descriptor_1               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_3_header_descriptor_1           ))
#define rgPCIe_AXI_outregion_3_region_base_addr                  (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_3_region_base_addr              ))
#define rgPCIe_AXI_outregion_4_addr_translation_0                (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_4_addr_translation_0            ))
#define rgPCIe_AXI_outregion_4_addr_translation_1                (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_4_addr_translation_1            ))
#define rgPCIe_AXI_outregion_4_header_descriptor_0               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_4_header_descriptor_0           ))
#define rgPCIe_AXI_outregion_4_header_descriptor_1               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_4_header_descriptor_1           ))
#define rgPCIe_AXI_outregion_4_region_base_addr                  (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_4_region_base_addr              ))
#define rgPCIe_AXI_outregion_5_addr_translation_0                (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_5_addr_translation_0            ))
#define rgPCIe_AXI_outregion_5_addr_translation_1                (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_5_addr_translation_1            ))
#define rgPCIe_AXI_outregion_5_header_descriptor_0               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_5_header_descriptor_0           ))
#define rgPCIe_AXI_outregion_5_header_descriptor_1               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_5_header_descriptor_1           ))
#define rgPCIe_AXI_outregion_5_region_base_addr                  (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_5_region_base_addr              ))
#define rgPCIe_AXI_outregion_6_addr_translation_0                (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_6_addr_translation_0            ))
#define rgPCIe_AXI_outregion_6_addr_translation_1                (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_6_addr_translation_1            ))
#define rgPCIe_AXI_outregion_6_header_descriptor_0               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_6_header_descriptor_0           ))
#define rgPCIe_AXI_outregion_6_header_descriptor_1               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_6_header_descriptor_1           ))
#define rgPCIe_AXI_outregion_6_region_base_addr                  (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_6_region_base_addr              ))
#define rgPCIe_AXI_outregion_7_addr_translation_0                (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_7_addr_translation_0            ))
#define rgPCIe_AXI_outregion_7_addr_translation_1                (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_7_addr_translation_1            ))
#define rgPCIe_AXI_outregion_7_header_descriptor_0               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_7_header_descriptor_0           ))
#define rgPCIe_AXI_outregion_7_header_descriptor_1               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_7_header_descriptor_1           ))
#define rgPCIe_AXI_outregion_7_region_base_addr                  (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_7_region_base_addr              ))
#define rgPCIe_AXI_outregion_8_addr_translation_0                (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_8_addr_translation_0            ))
#define rgPCIe_AXI_outregion_8_addr_translation_1                (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_8_addr_translation_1            ))
#define rgPCIe_AXI_outregion_8_header_descriptor_0               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_8_header_descriptor_0           ))
#define rgPCIe_AXI_outregion_8_header_descriptor_1               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_8_header_descriptor_1           ))
#define rgPCIe_AXI_outregion_8_region_base_addr                  (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_8_region_base_addr              ))
#define rgPCIe_AXI_outregion_9_addr_translation_0                (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_9_addr_translation_0            ))
#define rgPCIe_AXI_outregion_9_addr_translation_1                (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_9_addr_translation_1            ))
#define rgPCIe_AXI_outregion_9_header_descriptor_0               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_9_header_descriptor_0           ))
#define rgPCIe_AXI_outregion_9_header_descriptor_1               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_9_header_descriptor_1           ))
#define rgPCIe_AXI_outregion_9_region_base_addr                  (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_9_region_base_addr              ))
#define rgPCIe_AXI_outregion_10_addr_translation_0               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_10_addr_translation_0           ))
#define rgPCIe_AXI_outregion_10_addr_translation_1               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_10_addr_translation_1           ))
#define rgPCIe_AXI_outregion_10_header_descriptor_0              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_10_header_descriptor_0          ))
#define rgPCIe_AXI_outregion_10_header_descriptor_1              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_10_header_descriptor_1          ))
#define rgPCIe_AXI_outregion_10_region_base_addr                 (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_10_region_base_addr             ))
#define rgPCIe_AXI_outregion_11_addr_translation_0               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_11_addr_translation_0           ))
#define rgPCIe_AXI_outregion_11_addr_translation_1               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_11_addr_translation_1           ))
#define rgPCIe_AXI_outregion_11_header_descriptor_0              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_11_header_descriptor_0          ))
#define rgPCIe_AXI_outregion_11_header_descriptor_1              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_11_header_descriptor_1          ))
#define rgPCIe_AXI_outregion_11_region_base_addr                 (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_11_region_base_addr             ))
#define rgPCIe_AXI_outregion_12_addr_translation_0               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_12_addr_translation_0           ))
#define rgPCIe_AXI_outregion_12_addr_translation_1               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_12_addr_translation_1           ))
#define rgPCIe_AXI_outregion_12_header_descriptor_0              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_12_header_descriptor_0          ))
#define rgPCIe_AXI_outregion_12_header_descriptor_1              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_12_header_descriptor_1          ))
#define rgPCIe_AXI_outregion_12_region_base_addr                 (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_12_region_base_addr             ))
#define rgPCIe_AXI_outregion_13_addr_translation_0               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_13_addr_translation_0           ))
#define rgPCIe_AXI_outregion_13_addr_translation_1               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_13_addr_translation_1           ))
#define rgPCIe_AXI_outregion_13_header_descriptor_0              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_13_header_descriptor_0          ))
#define rgPCIe_AXI_outregion_13_header_descriptor_1              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_13_header_descriptor_1          ))
#define rgPCIe_AXI_outregion_13_region_base_addr                 (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_13_region_base_addr             ))
#define rgPCIe_AXI_outregion_14_addr_translation_0               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_14_addr_translation_0           ))
#define rgPCIe_AXI_outregion_14_addr_translation_1               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_14_addr_translation_1           ))
#define rgPCIe_AXI_outregion_14_header_descriptor_0              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_14_header_descriptor_0          ))
#define rgPCIe_AXI_outregion_14_header_descriptor_1              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_14_header_descriptor_1          ))
#define rgPCIe_AXI_outregion_14_region_base_addr                 (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_14_region_base_addr             ))
#define rgPCIe_AXI_outregion_15_addr_translation_0               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_15_addr_translation_0           ))
#define rgPCIe_AXI_outregion_15_addr_translation_1               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_15_addr_translation_1           ))
#define rgPCIe_AXI_outregion_15_header_descriptor_0              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_15_header_descriptor_0          ))
#define rgPCIe_AXI_outregion_15_header_descriptor_1              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_15_header_descriptor_1          ))
#define rgPCIe_AXI_outregion_15_region_base_addr                 (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_15_region_base_addr             ))
#define rgPCIe_AXI_outregion_16_addr_translation_0               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_16_addr_translation_0           ))
#define rgPCIe_AXI_outregion_16_addr_translation_1               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_16_addr_translation_1           ))
#define rgPCIe_AXI_outregion_16_header_descriptor_0              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_16_header_descriptor_0          ))
#define rgPCIe_AXI_outregion_16_header_descriptor_1              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_16_header_descriptor_1          ))
#define rgPCIe_AXI_outregion_16_region_base_addr                 (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_16_region_base_addr             ))
#define rgPCIe_AXI_outregion_17_addr_translation_0               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_17_addr_translation_0           ))
#define rgPCIe_AXI_outregion_17_addr_translation_1               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_17_addr_translation_1           ))
#define rgPCIe_AXI_outregion_17_header_descriptor_0              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_17_header_descriptor_0          ))
#define rgPCIe_AXI_outregion_17_header_descriptor_1              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_17_header_descriptor_1          ))
#define rgPCIe_AXI_outregion_17_region_base_addr                 (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_17_region_base_addr             ))
#define rgPCIe_AXI_outregion_18_addr_translation_0               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_18_addr_translation_0           ))
#define rgPCIe_AXI_outregion_18_addr_translation_1               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_18_addr_translation_1           ))
#define rgPCIe_AXI_outregion_18_header_descriptor_0              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_18_header_descriptor_0          ))
#define rgPCIe_AXI_outregion_18_header_descriptor_1              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_18_header_descriptor_1          ))
#define rgPCIe_AXI_outregion_18_region_base_addr                 (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_18_region_base_addr             ))
#define rgPCIe_AXI_outregion_19_addr_translation_0               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_19_addr_translation_0           ))
#define rgPCIe_AXI_outregion_19_addr_translation_1               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_19_addr_translation_1           ))
#define rgPCIe_AXI_outregion_19_header_descriptor_0              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_19_header_descriptor_0          ))
#define rgPCIe_AXI_outregion_19_header_descriptor_1              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_19_header_descriptor_1          ))
#define rgPCIe_AXI_outregion_19_region_base_addr                 (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_19_region_base_addr             ))
#define rgPCIe_AXI_outregion_20_addr_translation_0               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_20_addr_translation_0           ))
#define rgPCIe_AXI_outregion_20_addr_translation_1               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_20_addr_translation_1           ))
#define rgPCIe_AXI_outregion_20_header_descriptor_0              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_20_header_descriptor_0          ))
#define rgPCIe_AXI_outregion_20_header_descriptor_1              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_20_header_descriptor_1          ))
#define rgPCIe_AXI_outregion_20_region_base_addr                 (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_20_region_base_addr             ))
#define rgPCIe_AXI_outregion_21_addr_translation_0               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_21_addr_translation_0           ))
#define rgPCIe_AXI_outregion_21_addr_translation_1               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_21_addr_translation_1           ))
#define rgPCIe_AXI_outregion_21_header_descriptor_0              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_21_header_descriptor_0          ))
#define rgPCIe_AXI_outregion_21_header_descriptor_1              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_21_header_descriptor_1          ))
#define rgPCIe_AXI_outregion_21_region_base_addr                 (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_21_region_base_addr             ))
#define rgPCIe_AXI_outregion_22_addr_translation_0               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_22_addr_translation_0           ))
#define rgPCIe_AXI_outregion_22_addr_translation_1               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_22_addr_translation_1           ))
#define rgPCIe_AXI_outregion_22_header_descriptor_0              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_22_header_descriptor_0          ))
#define rgPCIe_AXI_outregion_22_header_descriptor_1              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_22_header_descriptor_1          ))
#define rgPCIe_AXI_outregion_22_region_base_addr                 (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_22_region_base_addr             ))
#define rgPCIe_AXI_outregion_23_addr_translation_0               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_23_addr_translation_0           ))
#define rgPCIe_AXI_outregion_23_addr_translation_1               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_23_addr_translation_1           ))
#define rgPCIe_AXI_outregion_23_header_descriptor_0              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_23_header_descriptor_0          ))
#define rgPCIe_AXI_outregion_23_header_descriptor_1              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_23_header_descriptor_1          ))
#define rgPCIe_AXI_outregion_23_region_base_addr                 (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_23_region_base_addr             ))
#define rgPCIe_AXI_outregion_24_addr_translation_0               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_24_addr_translation_0           ))
#define rgPCIe_AXI_outregion_24_addr_translation_1               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_24_addr_translation_1           ))
#define rgPCIe_AXI_outregion_24_header_descriptor_0              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_24_header_descriptor_0          ))
#define rgPCIe_AXI_outregion_24_header_descriptor_1              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_24_header_descriptor_1          ))
#define rgPCIe_AXI_outregion_24_region_base_addr                 (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_24_region_base_addr             ))
#define rgPCIe_AXI_outregion_25_addr_translation_0               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_25_addr_translation_0           ))
#define rgPCIe_AXI_outregion_25_addr_translation_1               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_25_addr_translation_1           ))
#define rgPCIe_AXI_outregion_25_header_descriptor_0              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_25_header_descriptor_0          ))
#define rgPCIe_AXI_outregion_25_header_descriptor_1              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_25_header_descriptor_1          ))
#define rgPCIe_AXI_outregion_25_region_base_addr                 (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_25_region_base_addr             ))
#define rgPCIe_AXI_outregion_26_addr_translation_0               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_26_addr_translation_0           ))
#define rgPCIe_AXI_outregion_26_addr_translation_1               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_26_addr_translation_1           ))
#define rgPCIe_AXI_outregion_26_header_descriptor_0              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_26_header_descriptor_0          ))
#define rgPCIe_AXI_outregion_26_header_descriptor_1              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_26_header_descriptor_1          ))
#define rgPCIe_AXI_outregion_26_region_base_addr                 (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_26_region_base_addr             ))
#define rgPCIe_AXI_outregion_27_addr_translation_0               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_27_addr_translation_0           ))
#define rgPCIe_AXI_outregion_27_addr_translation_1               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_27_addr_translation_1           ))
#define rgPCIe_AXI_outregion_27_header_descriptor_0              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_27_header_descriptor_0          ))
#define rgPCIe_AXI_outregion_27_header_descriptor_1              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_27_header_descriptor_1          ))
#define rgPCIe_AXI_outregion_27_region_base_addr                 (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_27_region_base_addr             ))
#define rgPCIe_AXI_outregion_28_addr_translation_0               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_28_addr_translation_0           ))
#define rgPCIe_AXI_outregion_28_addr_translation_1               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_28_addr_translation_1           ))
#define rgPCIe_AXI_outregion_28_header_descriptor_0              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_28_header_descriptor_0          ))
#define rgPCIe_AXI_outregion_28_header_descriptor_1              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_28_header_descriptor_1          ))
#define rgPCIe_AXI_outregion_28_region_base_addr                 (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_28_region_base_addr             ))
#define rgPCIe_AXI_outregion_29_addr_translation_0               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_29_addr_translation_0           ))
#define rgPCIe_AXI_outregion_29_addr_translation_1               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_29_addr_translation_1           ))
#define rgPCIe_AXI_outregion_29_header_descriptor_0              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_29_header_descriptor_0          ))
#define rgPCIe_AXI_outregion_29_header_descriptor_1              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_29_header_descriptor_1          ))
#define rgPCIe_AXI_outregion_29_region_base_addr                 (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_29_region_base_addr             ))
#define rgPCIe_AXI_outregion_30_addr_translation_0               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_30_addr_translation_0           ))
#define rgPCIe_AXI_outregion_30_addr_translation_1               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_30_addr_translation_1           ))
#define rgPCIe_AXI_outregion_30_header_descriptor_0              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_30_header_descriptor_0          ))
#define rgPCIe_AXI_outregion_30_header_descriptor_1              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_30_header_descriptor_1          ))
#define rgPCIe_AXI_outregion_30_region_base_addr                 (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_30_region_base_addr             ))
#define rgPCIe_AXI_outregion_31_addr_translation_0               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_31_addr_translation_0           ))
#define rgPCIe_AXI_outregion_31_addr_translation_1               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_31_addr_translation_1           ))
#define rgPCIe_AXI_outregion_31_header_descriptor_0              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_31_header_descriptor_0          ))
#define rgPCIe_AXI_outregion_31_header_descriptor_1              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_31_header_descriptor_1          ))
#define rgPCIe_AXI_outregion_31_region_base_addr                 (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_outregion_31_region_base_addr             ))
#define rgPCIe_AXI_inregion_rc_bar_0_addr_translation            (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_inregion_rc_bar_0_addr_translation        ))
#define rgPCIe_AXI_inregion_rc_bar_1_addr_translation            (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_inregion_rc_bar_1_addr_translation        ))
#define rgPCIe_AXI_inregion_rc_bar_2_addr_translation            (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_inregion_rc_bar_2_addr_translation        ))
#define rgPCIe_AXI_l0                                            (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_l0                                        ))
#define rgPCIe_AXI_inregion_ep_bar_0_addr_translation            (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_inregion_ep_bar_0_addr_translation        ))
#define rgPCIe_AXI_inregion_ep_bar_1_addr_translation            (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_inregion_ep_bar_1_addr_translation        ))
#define rgPCIe_AXI_inregion_ep_bar_2_addr_translation            (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_inregion_ep_bar_2_addr_translation        ))
#define rgPCIe_AXI_inregion_ep_bar_3_addr_translation            (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_inregion_ep_bar_3_addr_translation        ))
#define rgPCIe_AXI_inregion_ep_bar_4_addr_translation            (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_inregion_ep_bar_4_addr_translation        ))
#define rgPCIe_AXI_inregion_ep_bar_5_addr_translation            (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_inregion_ep_bar_5_addr_translation        ))
#define rgPCIe_AXI_inregion_ep_bar_6_addr_translation            (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_AXIConfig + PCIe_AXI_inregion_ep_bar_6_addr_translation        ))

#define rgPCIe_DMA_channel_0_ctrl                                (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_DMAConfig + PCIe_DMA_channel_0_ctrl                            ))
#define rgPCIe_DMA_channel_0_sp_l                                (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_DMAConfig + PCIe_DMA_channel_0_sp_l                            ))
#define rgPCIe_DMA_channel_0_sp_u                                (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_DMAConfig + PCIe_DMA_channel_0_sp_u                            ))
#define rgPCIe_DMA_channel_0_attr_l                              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_DMAConfig + PCIe_DMA_channel_0_attr_l                          ))
#define rgPCIe_DMA_channel_0_attr_u                              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_DMAConfig + PCIe_DMA_channel_0_attr_u                          ))
#define rgPCIe_DMA_channel_1_ctrl                                (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_DMAConfig + PCIe_DMA_channel_1_ctrl                            ))
#define rgPCIe_DMA_channel_1_sp_l                                (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_DMAConfig + PCIe_DMA_channel_1_sp_l                            ))
#define rgPCIe_DMA_channel_1_sp_u                                (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_DMAConfig + PCIe_DMA_channel_1_sp_u                            ))
#define rgPCIe_DMA_channel_1_attr_l                              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_DMAConfig + PCIe_DMA_channel_1_attr_l                          ))
#define rgPCIe_DMA_channel_1_attr_u                              (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_DMAConfig + PCIe_DMA_channel_1_attr_u                          ))
#define rgPCIe_DMA_common_udma_int                               (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_DMAConfig + PCIe_DMA_common_udma_int                           ))
#define rgPCIe_DMA_common_udma_int_ena                           (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_DMAConfig + PCIe_DMA_common_udma_int_ena                       ))
#define rgPCIe_DMA_common_udma_int_dis                           (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_DMAConfig + PCIe_DMA_common_udma_int_dis                       ))
#define rgPCIe_DMA_common_udma_ib_ecc_uncorrectable_errors       (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_DMAConfig + PCIe_DMA_common_udma_ib_ecc_uncorrectable_errors   ))
#define rgPCIe_DMA_common_udma_ib_ecc_correctable_errors         (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_DMAConfig + PCIe_DMA_common_udma_ib_ecc_correctable_errors     ))
#define rgPCIe_DMA_common_udma_ob_ecc_uncorrectable_errors       (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_DMAConfig + PCIe_DMA_common_udma_ob_ecc_uncorrectable_errors   ))
#define rgPCIe_DMA_common_udma_ob_ecc_correctable_errors         (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_DMAConfig + PCIe_DMA_common_udma_ob_ecc_correctable_errors     ))
#define rgPCIe_DMA_common_udma_cap_ver                           (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_DMAConfig + PCIe_DMA_common_udma_cap_ver                       ))
#define rgPCIe_DMA_common_udma_config                            (*(volatile int*)(PCIE_CORE_BASE + PCIe_Core_DMAConfig + PCIe_DMA_common_udma_config                        ))

