#ifndef PLATFORM_BOOTHEADER_h
#define PLATFORM_BOOTHEADER_h

#define RUMBOOT_PLATFORM_CHIPID   3
#define RUMBOOT_PLATFORM_CHIPREV  1
#define RUMBOOT_PLATFORM_NUMCORES 1


#endif /* end of include guard: PLATFORM_BOOTHEADER_h */
