/*
 * crg.h
 *
 *  Created on: Mar 18, 2019
 *      Author: v.strukov
 */

#ifndef RUMBOOT_INCLUDE_PLATFORM_OI10_PLATFORM_REGS_FIELDS_CRG_H_
#define RUMBOOT_INCLUDE_PLATFORM_OI10_PLATFORM_REGS_FIELDS_CRG_H_

#include <rumboot/macros.h>

BEGIN_ENUM(CRG_RST_CFG2_FIELDS)
    DECLARE_ENUM_VAL(   CRG_RST_CFG2_FIELDS_RSTREQ0_MODE_i,      0 )
    DECLARE_ENUM_VAL(   CRG_RST_CFG2_FIELDS_RSTREQ0_MODE_n,      2 )
    DECLARE_ENUM_VAL(   CRG_RST_CFG2_FIELDS_RSTREQ0_MODE_mask,   FIELD_MASK32( CRG_RST_CFG2_FIELDS_RSTREQ0_MODE_i, CRG_RST_CFG2_FIELDS_RSTREQ0_MODE_n ) )

    DECLARE_ENUM_VAL(   CRG_RST_CFG2_FIELDS_RSTREQ1_MODE_i,      2 )
    DECLARE_ENUM_VAL(   CRG_RST_CFG2_FIELDS_RSTREQ1_MODE_n,      2 )
    DECLARE_ENUM_VAL(   CRG_RST_CFG2_FIELDS_RSTREQ1_MODE_mask,   FIELD_MASK32( CRG_RST_CFG2_FIELDS_RSTREQ1_MODE_i, CRG_RST_CFG2_FIELDS_RSTREQ1_MODE_n ) )

    DECLARE_ENUM_VAL(   CRG_RST_CFG2_FIELDS_RSTREQ2_MODE_i,      4 )
    DECLARE_ENUM_VAL(   CRG_RST_CFG2_FIELDS_RSTREQ2_MODE_n,      2 )
    DECLARE_ENUM_VAL(   CRG_RST_CFG2_FIELDS_RSTREQ2_MODE_mask,   FIELD_MASK32( CRG_RST_CFG2_FIELDS_RSTREQ2_MODE_i, CRG_RST_CFG2_FIELDS_RSTREQ2_MODE_n ) )

    DECLARE_ENUM_VAL(   CRG_RST_CFG2_FIELDS_RSTREQ0_MASK_i,      16 )
    DECLARE_ENUM_VAL(   CRG_RST_CFG2_FIELDS_RSTREQ0_MASK_n,      1 )
    DECLARE_ENUM_VAL(   CRG_RST_CFG2_FIELDS_RSTREQ0_MASK_mask,   FIELD_MASK32( CRG_RST_CFG2_FIELDS_RSTREQ0_MASK_i, CRG_RST_CFG2_FIELDS_RSTREQ0_MASK_n ) )

    DECLARE_ENUM_VAL(   CRG_RST_CFG2_FIELDS_RSTREQ1_MASK_i,      17 )
    DECLARE_ENUM_VAL(   CRG_RST_CFG2_FIELDS_RSTREQ1_MASK_n,      1 )
    DECLARE_ENUM_VAL(   CRG_RST_CFG2_FIELDS_RSTREQ1_MASK_mask,   FIELD_MASK32( CRG_RST_CFG2_FIELDS_RSTREQ1_MASK_i, CRG_RST_CFG2_FIELDS_RSTREQ1_MASK_n ) )

    DECLARE_ENUM_VAL(   CRG_RST_CFG2_FIELDS_RSTREQ2_MASK_i,      18 )
    DECLARE_ENUM_VAL(   CRG_RST_CFG2_FIELDS_RSTREQ2_MASK_n,      1 )
    DECLARE_ENUM_VAL(   CRG_RST_CFG2_FIELDS_RSTREQ2_MASK_mask,   FIELD_MASK32( CRG_RST_CFG2_FIELDS_RSTREQ2_MASK_i, CRG_RST_CFG2_FIELDS_RSTREQ2_MASK_n ) )

    DECLARE_ENUM_VAL(   CRG_RST_CFG2_FIELDS_RSTREQ_BYP_i,        24 )
    DECLARE_ENUM_VAL(   CRG_RST_CFG2_FIELDS_RSTREQ_BYP_n,        1 )
    DECLARE_ENUM_VAL(   CRG_RST_CFG2_FIELDS_RSTREQ_BYP_mask,     FIELD_MASK32( CRG_RST_CFG2_FIELDS_RSTREQ_BYP_i, CRG_RST_CFG2_FIELDS_RSTREQ_BYP_n ) )

END_ENUM(CRG_RST_CFG2_FIELDS)

BEGIN_ENUM(CRG_RST_CFG2_MODE)
    DECLARE_ENUM_VAL(   CRG_RST_CFG2_MODE_ARESETn,              0)
    DECLARE_ENUM_VAL(   CRG_RST_CFG2_MODE_ARESETn_NRST_SYS,     1)
    DECLARE_ENUM_VAL(   CRG_RST_CFG2_MODE_ARESETn_CRG_RSTN,     2)
    DECLARE_ENUM_VAL(   CRG_RST_CFG2_MODE_ALL_RST,              3)
END_ENUM(CRG_RST_CFG2_MODE)

BEGIN_ENUM(CRG_RST_MON_FIELDS)
    DECLARE_ENUM_VAL(   CRG_RST_MON_FIELDS_RST_REQ0_i,          0 )
    DECLARE_ENUM_VAL(   CRG_RST_MON_FIELDS_RST_REQ0_n,          1 )
    DECLARE_ENUM_VAL(   CRG_RST_MON_FIELDS_RST_REQ0_mask,       FIELD_MASK32( CRG_RST_MON_FIELDS_RST_REQ0_i, CRG_RST_MON_FIELDS_RST_REQ0_n ) )

    DECLARE_ENUM_VAL(   CRG_RST_MON_FIELDS_RST_REQ1_i,          1 )
    DECLARE_ENUM_VAL(   CRG_RST_MON_FIELDS_RST_REQ1_n,          1 )
    DECLARE_ENUM_VAL(   CRG_RST_MON_FIELDS_RST_REQ1_mask,       FIELD_MASK32( CRG_RST_MON_FIELDS_RST_REQ1_i, CRG_RST_MON_FIELDS_RST_REQ1_n ) )

    DECLARE_ENUM_VAL(   CRG_RST_MON_FIELDS_RST_REQ2_i,          2 )
    DECLARE_ENUM_VAL(   CRG_RST_MON_FIELDS_RST_REQ2_n,          1 )
    DECLARE_ENUM_VAL(   CRG_RST_MON_FIELDS_RST_REQ2_mask,       FIELD_MASK32( CRG_RST_MON_FIELDS_RST_REQ2_i, CRG_RST_MON_FIELDS_RST_REQ2_n ) )

    DECLARE_ENUM_VAL(   CRG_RST_MON_FIELDS_RST_REQ_MODE0_i,     8 )
    DECLARE_ENUM_VAL(   CRG_RST_MON_FIELDS_RST_REQ_MODE0_n,     1 )
    DECLARE_ENUM_VAL(   CRG_RST_MON_FIELDS_RST_REQ_MODE0_mask,  FIELD_MASK32( CRG_RST_MON_FIELDS_RST_REQ_MODE0_i, CRG_RST_MON_FIELDS_RST_REQ_MODE0_n ) )

    DECLARE_ENUM_VAL(   CRG_RST_MON_FIELDS_RST_REQ_MODE1_i,     9 )
    DECLARE_ENUM_VAL(   CRG_RST_MON_FIELDS_RST_REQ_MODE1_n,     1 )
    DECLARE_ENUM_VAL(   CRG_RST_MON_FIELDS_RST_REQ_MODE1_mask,  FIELD_MASK32( CRG_RST_MON_FIELDS_RST_REQ_MODE1_i, CRG_RST_MON_FIELDS_RST_REQ_MODE1_n ) )

    DECLARE_ENUM_VAL(   CRG_RST_MON_FIELDS_RST_SYS_MON_i,       10 )
    DECLARE_ENUM_VAL(   CRG_RST_MON_FIELDS_RST_SYS_MON_n,       1 )
    DECLARE_ENUM_VAL(   CRG_RST_MON_FIELDS_RST_SYS_MON_mask,    FIELD_MASK32( CRG_RST_MON_FIELDS_RST_SYS_MON_i, CRG_RST_MON_FIELDS_RST_SYS_MON_n ) )

    DECLARE_ENUM_VAL(   CRG_RST_MON_FIELDS_RST_POR_MON_i,       11 )
    DECLARE_ENUM_VAL(   CRG_RST_MON_FIELDS_RST_POR_MON_n,       1 )
    DECLARE_ENUM_VAL(   CRG_RST_MON_FIELDS_RST_POR_MON_mask,    FIELD_MASK32( CRG_RST_MON_FIELDS_RST_POR_MON_i, CRG_RST_MON_FIELDS_RST_POR_MON_n ) )

END_ENUM(CRG_RST_MON_FIELDS)

#endif /* RUMBOOT_INCLUDE_PLATFORM_OI10_PLATFORM_REGS_FIELDS_CRG_H_ */
