/*
 * itrace.h
 *
 *  Created on: Feb 7, 2019
 *      Author: a.gurov
 */

#ifndef ITRACE_H_
#define ITRACE_H_

#include <platform/common_macros/common_macros.h>
#include <platform/arch/ppc/ibm_bit_ordering_macros.h>

BEGIN_ENUM( ITC0_TC_FIELD )
    DECLARE_ENUM_VAL( ITC0_TC_ITE_e,    0  )
    DECLARE_ENUM_VAL( ITC0_TC_ITCT_e,   1  )
    DECLARE_ENUM_VAL( ITC0_TC_ITTM_e,   3  )
    DECLARE_ENUM_VAL( ITC0_TC_SS_e,     4  )
    DECLARE_ENUM_VAL( ITC0_TC_ITIM_e,   8  )
    DECLARE_ENUM_VAL( ITC0_TC_ITETE_e,  9  )
    DECLARE_ENUM_VAL( ITC0_TC_ITPD_e,   10 )
    DECLARE_ENUM_VAL( ITC0_TC_ITE_i,    IBM_BIT_INDEX(32, ITC0_TC_ITE_e     ))
    DECLARE_ENUM_VAL( ITC0_TC_ITCT_i,   IBM_BIT_INDEX(32, ITC0_TC_ITCT_e    ))
    DECLARE_ENUM_VAL( ITC0_TC_ITTM_i,   IBM_BIT_INDEX(32, ITC0_TC_ITTM_e    ))
    DECLARE_ENUM_VAL( ITC0_TC_SS_i,     IBM_BIT_INDEX(32, ITC0_TC_SS_e      ))
    DECLARE_ENUM_VAL( ITC0_TC_ITIM_i,   IBM_BIT_INDEX(32, ITC0_TC_ITIM_e    ))
    DECLARE_ENUM_VAL( ITC0_TC_ITETE_i,  IBM_BIT_INDEX(32, ITC0_TC_ITETE_e   ))
    DECLARE_ENUM_VAL( ITC0_TC_ITPD_i,   IBM_BIT_INDEX(32, ITC0_TC_ITPD_e    ))
END_ENUM( ITC0_TC_FIELD )

BEGIN_ENUM( ITC0_TS_FIELD )
    DECLARE_ENUM_VAL( ITC0_TS_ITR_e,    0  )
    DECLARE_ENUM_VAL( ITC0_TS_ITT_e,    1  )
    DECLARE_ENUM_VAL( ITC0_TS_ITA1W_e,  2  )
    DECLARE_ENUM_VAL( ITC0_TS_ITA2W_e,  3  )
    DECLARE_ENUM_VAL( ITC0_TS_ITLBU_e,  4  )
    DECLARE_ENUM_VAL( ITC0_TS_ITTOO_e,  5  )
    DECLARE_ENUM_VAL( ITC0_TS_ITR_i,    IBM_BIT_INDEX(32, ITC0_TS_ITR_i     ))
    DECLARE_ENUM_VAL( ITC0_TS_ITT_i,    IBM_BIT_INDEX(32, ITC0_TS_ITT_i     ))
    DECLARE_ENUM_VAL( ITC0_TS_ITA1W_i,  IBM_BIT_INDEX(32, ITC0_TS_ITA1W_i   ))
    DECLARE_ENUM_VAL( ITC0_TS_ITA2W_i,  IBM_BIT_INDEX(32, ITC0_TS_ITA2W_i   ))
    DECLARE_ENUM_VAL( ITC0_TS_ITLBU_i,  IBM_BIT_INDEX(32, ITC0_TS_ITLBU_i   ))
    DECLARE_ENUM_VAL( ITC0_TS_ITTOO_i,  IBM_BIT_INDEX(32, ITC0_TS_ITTOO_i   ))
END_ENUM( ITC0_TS_FIELD )


#endif /* ITRACE_H_ */
