/*
 * itrace.h
 *
 *  Created on: Feb 7, 2019
 *      Author: a.gurov
 */

#ifndef REGS_FIELDS_ITRACE_H_
#define REGS_FIELDS_ITRACE_H_

#include <rumboot/macros.h>
#include <platform/arch/ppc/ibm_bit_ordering_macros.h>


BEGIN_ENUM( ITC0_TC_FIELD )
    DECLARE_ENUM_VAL( ITC0_TC_ITE_e,    0  )
    DECLARE_ENUM_VAL( ITC0_TC_ITCT_e,   2  )
    DECLARE_ENUM_VAL( ITC0_TC_ITTM_e,   3  )
    DECLARE_ENUM_VAL( ITC0_TC_SS_e,     7  )
    DECLARE_ENUM_VAL( ITC0_TC_ITIM_e,   8  )
    DECLARE_ENUM_VAL( ITC0_TC_ITETE_e,  9  )
    DECLARE_ENUM_VAL( ITC0_TC_ITPD_e,   10 )
    DECLARE_ENUM_VAL( ITC0_TC_ITE_i,    IBM_BIT_INDEX(32, ITC0_TC_ITE_e     ))
    DECLARE_ENUM_VAL( ITC0_TC_ITCT_i,   IBM_BIT_INDEX(32, ITC0_TC_ITCT_e    ))
    DECLARE_ENUM_VAL( ITC0_TC_ITTM_i,   IBM_BIT_INDEX(32, ITC0_TC_ITTM_e    ))
    DECLARE_ENUM_VAL( ITC0_TC_SS_i,     IBM_BIT_INDEX(32, ITC0_TC_SS_e      ))
    DECLARE_ENUM_VAL( ITC0_TC_ITIM_i,   IBM_BIT_INDEX(32, ITC0_TC_ITIM_e    ))
    DECLARE_ENUM_VAL( ITC0_TC_ITETE_i,  IBM_BIT_INDEX(32, ITC0_TC_ITETE_e   ))
    DECLARE_ENUM_VAL( ITC0_TC_ITPD_i,   IBM_BIT_INDEX(32, ITC0_TC_ITPD_e    ))
END_ENUM( ITC0_TC_FIELD )

BEGIN_ENUM( ITC0_TS_FIELD )
    DECLARE_ENUM_VAL( ITC0_TS_ITR_e,    0  )
    DECLARE_ENUM_VAL( ITC0_TS_ITT_e,    1  )
    DECLARE_ENUM_VAL( ITC0_TS_ITA1W_e,  2  )
    DECLARE_ENUM_VAL( ITC0_TS_ITA2W_e,  3  )
    DECLARE_ENUM_VAL( ITC0_TS_ITLBU_e,  4  )
    DECLARE_ENUM_VAL( ITC0_TS_ITTOO_e,  5  )
    DECLARE_ENUM_VAL( ITC0_TS_ITR_i,    IBM_BIT_INDEX(32, ITC0_TS_ITR_e     ))
    DECLARE_ENUM_VAL( ITC0_TS_ITT_i,    IBM_BIT_INDEX(32, ITC0_TS_ITT_e     ))
    DECLARE_ENUM_VAL( ITC0_TS_ITA1W_i,  IBM_BIT_INDEX(32, ITC0_TS_ITA1W_e   ))
    DECLARE_ENUM_VAL( ITC0_TS_ITA2W_i,  IBM_BIT_INDEX(32, ITC0_TS_ITA2W_e   ))
    DECLARE_ENUM_VAL( ITC0_TS_ITLBU_i,  IBM_BIT_INDEX(32, ITC0_TS_ITLBU_e   ))
    DECLARE_ENUM_VAL( ITC0_TS_ITTOO_i,  IBM_BIT_INDEX(32, ITC0_TS_ITTOO_e   ))
END_ENUM( ITC0_TS_FIELD )

BEGIN_ENUM( ITC0_CxMH_FIELD )
    DECLARE_ENUM_VAL( ITC0_CxMH_EE0_e,  0  )
    DECLARE_ENUM_VAL( ITC0_CxMH_EE1_e,  1  )
    DECLARE_ENUM_VAL( ITC0_CxMH_TET0_e, 15 )
    DECLARE_ENUM_VAL( ITC0_CxMH_TET1_e, 31 )
    DECLARE_ENUM_VAL( ITC0_CxMH_EE0_i,  IBM_BIT_INDEX(32, ITC0_CxMH_EE0_e   ))
    DECLARE_ENUM_VAL( ITC0_CxMH_EE1_i,  IBM_BIT_INDEX(32, ITC0_CxMH_EE1_e   ))
    DECLARE_ENUM_VAL( ITC0_CxMH_TET0_i, IBM_BIT_INDEX(32, ITC0_CxMH_TET0_e  ))
    DECLARE_ENUM_VAL( ITC0_CxMH_TET1_i, IBM_BIT_INDEX(32, ITC0_CxMH_TET1_e  ))
END_ENUM( ITC0_CxMH_FIELD )

BEGIN_ENUM( ITC0_ITLA1_FIELD )
    DECLARE_ENUM_VAL( ITC0_ITLA1_n, 32 )
    DECLARE_ENUM_VAL( ITC0_ITLA1_e, 31 )
    DECLARE_ENUM_VAL( ITC0_ITLA1_i, IBM_BIT_INDEX( 32, ITC0_ITLA1_e ) )
END_ENUM( ITC0_ITLA1_FIELD )

BEGIN_ENUM( ITC0_ITLA2_FIELD )
    DECLARE_ENUM_VAL( ITC0_ITLA2_n,         32 )
    DECLARE_ENUM_VAL( ITC0_ITLA2_e,         31 )
    DECLARE_ENUM_VAL( ITC0_ITLA2_i,         IBM_BIT_INDEX( 32, ITC0_ITLA2_e ) )
    DECLARE_ENUM_VAL( ITC0_ITLA2_VALID_n,   1 )
    DECLARE_ENUM_VAL( ITC0_ITLA2_VALID_e,   18 )
    DECLARE_ENUM_VAL( ITC0_ITLA2_VALID_i,   IBM_BIT_INDEX( 32, ITC0_ITLA2_VALID_e ) )
END_ENUM( ITC0_ITLA2_FIELD )


#endif /* REGS_FIELDS_ITRACE_H_ */
